## 46-881 Class 6

### Python pandas: Data Exploration and Wrangling (Part 2)

Amr Farahat

CMU / Tepper

2022-12-05

---

## Combining DataFrames

In [1]:
import numpy as np
import pandas as pd

#### Creating small dataframes for illustrative purposes

In [2]:
df_pop1 = pd.DataFrame({"state": ["Pennsylvania", "Ohio"],
                       "population": [12801989, 11689100]})
df_pop1

          state  population
0  Pennsylvania    12801989
1          Ohio    11689100

In [3]:
df_pop2 = pd.DataFrame({"state": ["New Jersey", "New York"],
                        "population": [8882190, 19453561]})
df_pop2

        state  population
0  New Jersey     8882190
1    New York    19453561

In [4]:
df_vax = pd.DataFrame({"state": ["Pennsylvania", "Ohio", "New York", "West Virginia"],
                       "people_fully_vaccinated": [9117526, 6969367, 15391715, 1056958]})
df_vax

           state  people_fully_vaccinated
0   Pennsylvania                  9117526
1           Ohio                  6969367
2       New York                 15391715
3  West Virginia                  1056958

#### Binding (concatenating) rows or columns of two dataframes

In [5]:
df_pop = pd.concat([df_pop1,df_pop2])

In [7]:
df_pop

          state  population
0  Pennsylvania    12801989
1          Ohio    11689100
0    New Jersey     8882190
1      New York    19453561

#### Joining two dataframes

In [9]:
pd.merge(df_pop, df_vax, on="state")

          state  population  people_fully_vaccinated
0  Pennsylvania    12801989                  9117526
1          Ohio    11689100                  6969367
2      New York    19453561                 15391715

In [10]:
pd.merge(df_pop, df_vax, on="state", how="inner") ## inner is default. See above

          state  population  people_fully_vaccinated
0  Pennsylvania    12801989                  9117526
1          Ohio    11689100                  6969367
2      New York    19453561                 15391715

By default, pandas.merge does an "inner" join

Types of merge (joins): inner, left, right, outer

In [11]:
pd.merge(df_pop, df_vax, on="state", how="left")

          state  population  people_fully_vaccinated
0  Pennsylvania    12801989                9117526.0
1          Ohio    11689100                6969367.0
2    New Jersey     8882190                      NaN
3      New York    19453561               15391715.0

In [12]:
pd.merge(df_pop, df_vax, on="state", how="right")

           state  population  people_fully_vaccinated
0   Pennsylvania  12801989.0                  9117526
1           Ohio  11689100.0                  6969367
2       New York  19453561.0                 15391715
3  West Virginia         NaN                  1056958

In [13]:
pd.merge(df_pop, df_vax, on="state", how="outer")

           state  population  people_fully_vaccinated
0   Pennsylvania  12801989.0                9117526.0
1           Ohio  11689100.0                6969367.0
2     New Jersey   8882190.0                      NaN
3       New York  19453561.0               15391715.0
4  West Virginia         NaN                1056958.0

---
## END