## 46-881 Class 6

### Python pandas: Data Exploration and Wrangling (Part 2)

Amr Farahat

CMU / Tepper

2022-12-05

---

## Handling NA values

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("covid19_US_V.csv", )

### Identifying NA values

In [3]:
df

,state,date,vaccination_rate,people_fully_vaccinated,population
0,Northern Mariana Islands,2020-03-16,NaN,NaN,55144
1,Northern Mariana Islands,2020-03-17,NaN,NaN,55144
2,Northern Mariana Islands,2020-03-18,NaN,NaN,55144
3,Northern Mariana Islands,2020-03-19,NaN,NaN,55144
4,Northern Mariana Islands,2020-03-20,NaN,NaN,55144
...,...,...,...,...,...
55108,Colorado,2022-10-22,NaN,NaN,5758736
55109,Colorado,2022-10-23,NaN,NaN,5758736
55110,Colorado,2022-10-24,NaN,NaN,5758736
55111,Colorado,2022-10-25,NaN,NaN,5758736
55112,Colorado,2022-10-26,NaN,NaN,5758736

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55113 entries, 0 to 55112
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   state                    55113 non-null  object
 1   date                     55113 non-null  object
 2   vaccination_rate         37800 non-null  float64
 3   people_fully_vaccinated  37800 non-null  float64
 4   population               55113 non-null  int64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.1+ MB

In [5]:
df.isna()

       state   date  vaccination_rate  people_fully_vaccinated  population
0      False  False              True                     True       False
1      False  False              True                     True       False
2      False  False              True                     True       False
3      False  False              True                     True       False
4      False  False              True                     True       False
...      ...    ...               ...                      ...         ...
55108  False  False              True                     True       False
55109  False  False              True                     True       False
55110  False  False              True                     True       False
55111  False  False              True                     True       False
55112  False  False              True                     True       False

[55113 rows x 5 columns]

In [6]:
df.isna()["vaccination_rate"]

0        True
1        True
2        True
3        True
4        True
         ...
55108    True
55109    True
55110    True
55111    True
55112    True
Name: vaccination_rate, Length: 55113, dtype: bool

In [7]:
df.isna()["vaccination_rate"].sum()

17313

In [8]:
df.notna()["vaccination_rate"].sum()

37800

In [9]:
#df.isna().any(axis=1)
df[df.isna().any(axis=1) == True]

,state,date,vaccination_rate,people_fully_vaccinated,population
0,Northern Mariana Islands,2020-03-16,NaN,NaN,55144
1,Northern Mariana Islands,2020-03-17,NaN,NaN,55144
2,Northern Mariana Islands,2020-03-18,NaN,NaN,55144
3,Northern Mariana Islands,2020-03-19,NaN,NaN,55144
4,Northern Mariana Islands,2020-03-20,NaN,NaN,55144
...,...,...,...,...,...
55108,Colorado,2022-10-22,NaN,NaN,5758736
55109,Colorado,2022-10-23,NaN,NaN,5758736
55110,Colorado,2022-10-24,NaN,NaN,5758736
55111,Colorado,2022-10-25,NaN,NaN,5758736
55112,Colorado,2022-10-26,NaN,NaN,5758736

### Note: pandas by default ignores NA values

In [10]:
df["vaccination_rate"].median()

55.58186572381299

In [11]:
df["vaccination_rate"].median(skipna=False)

nan

### Handling NA values

#### Option 0: Do nothing (and interpret summary stats / model fit accordingly)

#### Option 1: Filter out the NA values

By dropping rows where any of the values is NaN.

In [12]:
df.dropna()

,state,date,vaccination_rate,people_fully_vaccinated,population
272,Northern Mariana Islands,2020-12-13,0.000000,0.0,55144
273,Northern Mariana Islands,2020-12-14,0.000000,0.0,55144
274,Northern Mariana Islands,2020-12-15,0.000000,0.0,55144
275,Northern Mariana Islands,2020-12-16,0.000000,0.0,55144
276,Northern Mariana Islands,2020-12-17,0.000000,0.0,55144
...,...,...,...,...,...
55100,Colorado,2022-10-14,72.369423,4167564.0,5758736
55101,Colorado,2022-10-15,72.378383,4168080.0,5758736
55102,Colorado,2022-10-16,72.379217,4168128.0,5758736
55103,Colorado,2022-10-17,72.380224,4168186.0,5758736
55104,Colorado,2022-10-18,72.380241,4168187.0,5758736

Or, by dropping only rows where *all* of the values are NaN.

In [15]:
df.dropna(how="all")

,state,date,vaccination_rate,people_fully_vaccinated,population
0,Northern Mariana Islands,2020-03-16,NaN,NaN,55144
1,Northern Mariana Islands,2020-03-17,NaN,NaN,55144
2,Northern Mariana Islands,2020-03-18,NaN,NaN,55144
3,Northern Mariana Islands,2020-03-19,NaN,NaN,55144
4,Northern Mariana Islands,2020-03-20,NaN,NaN,55144
...,...,...,...,...,...
55108,Colorado,2022-10-22,NaN,NaN,5758736
55109,Colorado,2022-10-23,NaN,NaN,5758736
55110,Colorado,2022-10-24,NaN,NaN,5758736
55111,Colorado,2022-10-25,NaN,NaN,5758736
55112,Colorado,2022-10-26,NaN,NaN,5758736

#### Option 2 (advanced): Impute the NA values in numerical columns

Usually requires some modeling...
The simplest case is to replace with the average (or median value)

In [16]:
df["vaccination_rate"].fillna(df["vaccination_rate"].mean())

0        50.101564
1        50.101564
2        50.101564
3        50.101564
4        50.101564
           ...
55108    50.101564
55109    50.101564
55110    50.101564
55111    50.101564
55112    50.101564
Name: vaccination_rate, Length: 55113, dtype: float64

---
## END