## 46-881 Class 6

### Python pandas: Data Exploration and Wrangling (Part 2)

Amr Farahat

CMU / Tepper

2022-12-05

---

## Pandas Pivot Tables

Also, see Chapter 10 of https://wesmckinney.com/book/.

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("PIT_rideshare_dataset.csv")

In [7]:
df.columns

Index(['rentals', 'month', 'day', 'hour', 'day_of_week', 'temperature',
       'humidity', 'windspeed', 'precipitation'],
      dtype='object')

In [8]:
df.pivot_table(index="month", aggfunc="mean")

,day,hour,humidity,precipitation,rentals,temperature,windspeed
month,,,,,,,
Apr,15.500000,11.500000,60.741667,0.003250,15.533333,52.451389,7.987288
Aug,16.000000,11.500000,76.736559,0.008345,18.439516,73.844086,5.110656
Dec,16.000000,11.500000,65.657258,0.005685,6.021505,42.384409,8.039031
Feb,14.500000,11.500000,73.072917,0.004390,3.377976,29.220238,8.049107
Jan,16.000000,11.500000,75.334677,0.002450,3.389785,31.198925,7.637954
Jul,16.000000,11.500000,72.495968,0.006075,19.934140,73.096774,6.120760
Jun,15.500000,11.500000,69.436111,0.010347,19.077778,71.547222,6.824022
Mar,16.002692,11.512786,52.648721,0.004320,13.220727,46.009421,8.787466
May,16.000000,11.500000,62.463710,0.004516,17.287634,60.286290,5.998638
Nov,15.500000,11.500000,60.762500,0.001111,10.468056,42.100000,7.885475
Oct,16.000000,11.500000,76.275538,0.006048,19.114247,60.463710,6.450135
Sep,15.500000,11.500000,73.109705,0.006139,22.798611,66.672293,7.142254

In [9]:
df.pivot_table(index="month", aggfunc = "count")

,day,day_of_week,hour,humidity,precipitation,rentals,temperature,windspeed
month,,,,,,,,
Apr,720,720,720,720,720,720,720,708
Aug,744,744,744,744,743,744,744,732
Dec,744,744,744,744,744,744,744,743
Feb,672,672,672,672,672,672,672,672
Jan,744,744,744,744,743,744,744,743
Jul,744,744,744,744,744,744,744,737
Jun,720,720,720,720,720,720,720,716
Mar,743,743,743,743,743,743,743,734
May,744,744,744,744,733,744,744,734
Nov,720,720,720,720,720,720,720,716
Oct,744,744,744,744,744,744,744,742
Sep,720,720,720,711,720,720,711,710

In [10]:
df.pivot_table(index="month", aggfunc = "count", values=["rentals","temperature"])

       rentals  temperature
month
Apr        720          720
Aug        744          744
Dec        744          744
Feb        672          672
Jan        744          744
Jul        744          744
Jun        720          720
Mar        743          743
May        744          744
Nov        720          720
Oct        744          744
Sep        720          711

In [11]:
df.pivot_table(index=["month", "day_of_week"], aggfunc = "mean", values=["rentals","temperature"])

                     rentals  temperature
month day_of_week
Apr   Fri          12.141667    46.675000
      Mon          12.947917    52.354167
      Sat          22.510417    49.770833
      Sun          19.562500    53.333333
      Thu           8.908333    49.125000
...                      ...          ...
Sep   Sat          31.322917    66.510417
      Sun          25.864583    68.031250
      Thu          21.716667    62.425000
      Tue          19.937500    70.386364
      Wed          15.458333    66.275000

[84 rows x 2 columns]

In [12]:
df.pivot_table(index=["month"], columns=["day_of_week"], aggfunc = "mean", values=["rentals"])

               rentals                                                         \
day_of_week        Fri        Mon        Sat        Sun        Thu        Tue
month
Apr          12.141667  12.947917  22.510417  19.562500   8.908333  19.406250
Aug          19.385417  16.025000  28.489583  22.866667  16.250000  13.866667
Dec           7.400000   4.729167   4.447917   6.593750   6.433333   5.833333
Feb           4.041667   2.114583   4.770833   3.218750   3.479167   2.968750
Jan           2.866667   3.093750   3.558333   2.541667   4.406250   3.687500
Jul          18.166667  17.447917  29.775000  26.135417  13.600000  16.927083
Jun          20.343750  13.447917  29.375000  23.791667  16.197917  17.550000
Mar          10.864583   9.783333  21.031250  14.768421   6.843750  13.808333
May          15.343750  15.383333  23.700000  20.625000  16.208333  14.510417
Nov           9.843750  11.091667   9.812500   7.093750  10.489583  11.766667
Oct          17.083333  20.052083  19.625000  17.625000  20.000000  19.489583
Sep          24.958333  22.437500  31.322917  25.864583  21.716667  19.937500


day_of_week        Wed
month
Apr          15.760417
Aug          12.833333
Dec           6.216667
Feb           3.052083
Jan           3.875000
Jul          17.052083
Jun          14.391667
Mar          15.583333
May          13.281250
Nov          12.697917
Oct          20.677083
Sep          15.458333

In [13]:
df.pivot_table(index=["month"], columns=["day_of_week"], aggfunc = "mean", values=["rentals"], margins=True)

               rentals                                                         \
day_of_week        Fri        Mon        Sat        Sun        Thu        Tue
month
Apr          12.141667  12.947917  22.510417  19.562500   8.908333  19.406250
Aug          19.385417  16.025000  28.489583  22.866667  16.250000  13.866667
Dec           7.400000   4.729167   4.447917   6.593750   6.433333   5.833333
Feb           4.041667   2.114583   4.770833   3.218750   3.479167   2.968750
Jan           2.866667   3.093750   3.558333   2.541667   4.406250   3.687500
Jul          18.166667  17.447917  29.775000  26.135417  13.600000  16.927083
Jun          20.343750  13.447917  29.375000  23.791667  16.197917  17.550000
Mar          10.864583   9.783333  21.031250  14.768421   6.843750  13.808333
May          15.343750  15.383333  23.700000  20.625000  16.208333  14.510417
Nov           9.843750  11.091667   9.812500   7.093750  10.489583  11.766667
Oct          17.083333  20.052083  19.625000  17.625000  20.000000  19.489583
Sep          24.958333  22.437500  31.322917  25.864583  21.716667  19.937500
All          13.347484  12.432692  19.044872  15.893344  12.092147  13.384615


day_of_week        Wed        All
month
Apr          15.760417  15.533333
Aug          12.833333  18.439516
Dec           6.216667   6.021505
Feb           3.052083   3.377976
Jan           3.875000   3.389785
Jul          17.052083  19.934140
Jun          14.391667  19.077778
Mar          15.583333  13.220727
May          13.281250  17.287634
Nov          12.697917  10.468056
Oct          20.677083  19.114247
Sep          15.458333  22.798611
All          12.599359  14.111200

---
## END