## 46-881 Class 6

### Python pandas: Data Exploration and Wrangling (Part 2)

Amr Farahat

CMU / Tepper

2022-12-05

---

## Exploratory Data Analysis using Python Example: PIT Flight Departures

Data source: Bureau of Transportation Statistics.
Covers domestic flights only
https://www.transtats.bts.gov/DL_SelectFields.aspx?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr

The database contains scheduled and actual departure and arrival times reported by certified U.S. air carriers that account for at least one percent of domestic scheduled passenger revenues. The data is collected by the Office of Airline Information, Bureau of Transportation Statistics (BTS).

Use the exercise as an opportunity to review / reference / get familiar with Python's pandas package. References:
- <https://wesmckinney.com/book/>
- <https://pandas.pydata.org/>

### Section 0: Setting up

**Task 0.1**: Import the numpy and pandas libraries (also called packages or modules)

In [1]:
import numpy as np
import pandas as pd

**Task 0.2**: Load the dataset "PIT_2021.csv" into a dataframe labelled "df"

In [2]:
df = pd.read_csv("PIT_2021.csv")

**Task 0.3**: Run the code cell below to disable limits on the number of columns displayed in Jupyter (so you can scroll across and inspect all columns)

In [3]:
pd.options.display.max_columns = None

### Section 1: First glance at the data 
*To check its structure and that it was loaded properly...*

**Task 1.1**: Find the dimensions of "df"; that is, the number of rows and number of columns.

In [4]:
df.shape

(32620, 33)

**Task 1.2**: Display the list of column names of df.

In [5]:
df.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_CARRIER',
       'OP_CARRIER_FL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR',
       'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'DEP_TIME_BLK',
       'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15',
       'ARR_TIME_BLK', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY'],
      dtype='object')

**Task 1.3**: Inspect the first 5 rows and last 5 rows of df. Note the default index column 0 .. length-1.

In [6]:
df.head(5)

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1900.0,-1.0,0.0,0.0,1900-1959,2025,2023.0,-2.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,756.0,-4.0,0.0,0.0,0800-0859,921,904.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,754.0,-6.0,0.0,0.0,0800-0859,921,903.0,-18.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1245,1243.0,-2.0,0.0,0.0,1200-1259,1403,1339.0,-24.0,0.0,0.0,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,807.0,7.0,7.0,0.0,0800-0859,930,913.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail(5)

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,1639,1645.0,6.0,6.0,0.0,1600-1659,1859,1853.0,-6.0,0.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,838,833.0,-5.0,0.0,0.0,0800-0859,1022,1019.0,-3.0,0.0,0.0,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,610,604.0,-6.0,0.0,0.0,0600-0659,835,822.0,-13.0,0.0,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,1600,1704.0,64.0,64.0,1.0,1600-1659,1744,1841.0,57.0,57.0,1.0,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,EWR,"Newark, NJ",NJ,1635,1630.0,-5.0,0.0,0.0,1600-1659,1802,1812.0,10.0,10.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

**Task 1.4**: Run the info() method on df and observe the information on missing data.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32620 entries, 0 to 32619
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   YEAR                 32620 non-null  int64
 1   MONTH                32620 non-null  int64
 2   DAY_OF_MONTH         32620 non-null  int64
 3   DAY_OF_WEEK          32620 non-null  int64
 4   FL_DATE              32620 non-null  object
 5   OP_CARRIER           32620 non-null  object
 6   OP_CARRIER_FL_NUM    32620 non-null  int64
 7   ORIGIN               32620 non-null  object
 8   ORIGIN_CITY_NAME     32620 non-null  object
 9   ORIGIN_STATE_ABR     32620 non-null  object
 10  DEST                 32620 non-null  object
 11  DEST_CITY_NAME       32620 non-null  object
 12  DEST_STATE_ABR       32620 non-null  object
 13  CRS_DEP_TIME         32620 non-null  int64
 14  DEP_TIME             32177 non-null  float64
 15  DEP_DELAY            32177 non-null  float64
 16  DEP_DELAY_NEW        32177 non-null  float64
 17  DEP_DEL15            32177 non-null  float64
 18  DEP_TIME_BLK         32620 non-null  object
 19  CRS_ARR_TIME         32620 non-null  int64
 20  ARR_TIME             32161 non-null  float64
 21  ARR_DELAY            32089 non-null  float64
 22  ARR_DELAY_NEW        32089 non-null  float64
 23  ARR_DEL15            32089 non-null  float64
 24  ARR_TIME_BLK         32620 non-null  object
 25  CANCELLED            32620 non-null  float64
 26  CANCELLATION_CODE    454 non-null    object
 27  DIVERTED             32620 non-null  float64
 28  CARRIER_DELAY        4337 non-null   float64
 29  WEATHER_DELAY        4337 non-null   float64
 30  NAS_DELAY            4337 non-null   float64
 31  SECURITY_DELAY       4337 non-null   float64
 32  LATE_AIRCRAFT_DELAY  4337 non-null   float64
dtypes: float64(15), int64(7), object(11)
memory usage: 8.2+ MB

### Section 2: Exploring Departure Time Patterns

**Task 2.1**: Compute the number of flights departing each month. What do you observe? Hint: The simplest way is to use the "value_counts()" on the MONTH series; optionally, you may then choose to apply the  ".sort_index()" method for readability.

In [13]:
df.pivot_table(index=["MONTH"],aggfunc= "count", values=["OP_CARRIER"])

       OP_CARRIER
MONTH
1            1705
2            1520
3            2003
4            2135
5            2470
6            3005
7            3216
8            3162
9            3049
10           3409
11           3540
12           3406

In [14]:
df["MONTH"].value_counts().sort_index()

1     1705
2     1520
3     2003
4     2135
5     2470
6     3005
7     3216
8     3162
9     3049
10    3409
11    3540
12    3406
Name: MONTH, dtype: int64

**Task 2.2**: Compute the number of flights departing each day of the week (Monday through Sunday). What do you observe? Note (a): Monday=1, Sunday=7; Note (b): 2021 started on a Friday and ended on a Friday (so one more Friday in the year than the other week days). On average, which day(s) of the week are busiest in terms of departures.

In [16]:
df.pivot_table(index=["DAY_OF_WEEK"],aggfunc= "count", values=["OP_CARRIER"])

             OP_CARRIER
DAY_OF_WEEK
1                  4898
2                  4191
3                  4246
4                  5055
5                  4930
6                  4297
7                  5003

In [17]:
df["DAY_OF_WEEK"].value_counts().sort_index()

1    4898
2    4191
3    4246
4    5055
5    4930
6    4297
7    5003
Name: DAY_OF_WEEK, dtype: int64

**Task 2.3**: Compute the number of flights scheduled to depart each hour of the day. Hint: Use "DEP_TIME_BLK". What do you observe?

In [18]:
df.pivot_table(index=["DEP_TIME_BLK"],aggfunc= "count", values=["OP_CARRIER"])

              OP_CARRIER
DEP_TIME_BLK
0001-0559            630
0600-0659           4778
0700-0759           3336
0800-0859           2238
0900-0959           1114
1000-1059           1917
1100-1159           2399
1200-1259           2162
1300-1359           1916
1400-1459           1077
1500-1559           2004
1600-1659           2386
1700-1759           2231
1800-1859           1562
1900-1959           2037
2000-2059            690
2100-2159            137
2200-2259              6

**Task 2.4**: Compute the fraction of flights whose departure is delayed 15 or more mins for each hour of the day. What do you observe? Hint: Use the groupby() and mean() methods.

In [24]:
df.pivot_table(index=["DEP_TIME_BLK"],aggfunc= "mean", values=["DEP_DEL15"])

              DEP_DEL15
DEP_TIME_BLK
0001-0559      0.054226
0600-0659      0.056847
0700-0759      0.058519
0800-0859      0.067574
0900-0959      0.077768
1000-1059      0.074948
1100-1159      0.114346
1200-1259      0.141050
1300-1359      0.130458
1400-1459      0.173749
1500-1559      0.171616
1600-1659      0.199062
1700-1759      0.200091
1800-1859      0.229765
1900-1959      0.270216
2000-2059      0.230655
2100-2159      0.248062
2200-2259      0.333333

### Section 3: Exploring Carrier (Airline) Patterns

**Task 3.1**: How many airlines depart from PIT? Take a moment to familiarize yourself with these airline codes in the accompanying file "Carrier_sodes.xlsx".

In [26]:
df["OP_CARRIER"].unique()

array(['OO', 'UA', 'WN', 'YV', 'YX', '9E', 'AA', 'AS', 'B6', 'DL', 'F9',
       'G4', 'MQ', 'NK', 'OH'], dtype=object)

In [27]:
len(df["OP_CARRIER"].unique())

15

**Task 3.2**: Compute the number of departing flights flown by each airline. Hint: You may want to use the "groupby()" or pivot_table methods followed by the "size()" method. Optionally, you can add ".sort_values(ascending = False)" to the resulting summary for readability. Do you find anything surprising in this summary?

In [34]:
df["OP_CARRIER"].value_counts().sort_index().sort_values(ascending = False)

YX    8828
WN    7061
AA    3140
NK    2205
OO    2158
DL    2119
G4    1325
UA    1317
YV     949
OH     895
9E     859
MQ     743
B6     555
AS     308
F9     158
Name: OP_CARRIER, dtype: int64

In [35]:
df.pivot_table(index=["OP_CARRIER"], aggfunc = 'count', values = 'ORIGIN').sort_values(by=['ORIGIN'],ascending = False)

            ORIGIN
OP_CARRIER
YX            8828
WN            7061
AA            3140
NK            2205
OO            2158
DL            2119
G4            1325
UA            1317
YV             949
OH             895
9E             859
MQ             743
B6             555
AS             308
F9             158

**Task 3.3**: Compute the fraction of flights whose departure is delayed 15 or more mins for each airline operating out of PIT. Which airline(s) appear to have the best on-time performance? Which airine(s) appear to have the worst on-time performance?

In [39]:
df.pivot_table(index=["OP_CARRIER"],aggfunc= "mean", values=["DEP_DEL15"]).sort_values(by='DEP_DEL15')

            DEP_DEL15
OP_CARRIER
DL           0.069635
YX           0.079652
9E           0.088475
UA           0.088889
YV           0.114347
AA           0.140777
OO           0.155691
B6           0.156648
OH           0.157303
WN           0.174319
NK           0.178789
MQ           0.187755
AS           0.188119
G4           0.193949
F9           0.194805

### Section 4: A More Detailed Look at Airline Delay / On-Time Statistics

**Task 4.1**: Create two new columns in "df": "DEP_ON_TIME" and "ARR_ON_TIME". A flight is on time if it's not cancelled or diverted or past 15 (actually 14) minutes past schedule. Hint: You can create a logical expression and then convert, if you wish, to 0 (False) and 1 (True) using the ".astype(int)" method. You may want to inspect the resulting dataframe after adding the columns using head(), tail(), and/or .info.

In [44]:
df["ARR_ON_TIME"] = ((df["ARR_DEL15"] == 0) & (df["CANCELLED"] == 0) & (df["DIVERTED"] == 0)).astype(int)

In [46]:
df["DEP_ON_TIME"] = ((df["DEP_DEL15"] == 0) & (df["CANCELLED"] == 0) & (df["DIVERTED"] == 0)).astype(int)

In [47]:
df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,ARR_ON_TIME,DEP_ON_TIME
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1900.0,-1.0,0.0,0.0,1900-1959,2025,2023.0,-2.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,756.0,-4.0,0.0,0.0,0800-0859,921,904.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,754.0,-6.0,0.0,0.0,0800-0859,921,903.0,-18.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1245,1243.0,-2.0,0.0,0.0,1200-1259,1403,1339.0,-24.0,0.0,0.0,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,807.0,7.0,7.0,0.0,0800-0859,930,913.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,1639,1645.0,6.0,6.0,0.0,1600-1659,1859,1853.0,-6.0,0.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,838,833.0,-5.0,0.0,0.0,0800-0859,1022,1019.0,-3.0,0.0,0.0,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,610,604.0,-6.0,0.0,0.0,0600-0659,835,822.0,-13.0,0.0,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,1600,1704.0,64.0,64.0,1.0,1600-1659,1744,1841.0,57.0,57.0,1.0,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0,0,0
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,EWR,"Newark, NJ",NJ,1635,1630.0,-5.0,0.0,0.0,1600-1659,1802,1812.0,10.0,10.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1,1

**Task 4.2**: Now create the following list of delay / on-time performance-related columns.

**Task 4.3**: Create a table comparing all airlines in terms of these performance metrics (using the average of the columns). Sort the table based on "DEP_DEL15" as you've done in Task 2.3. Pause and examine carefully the results.

In [48]:
perf_cols = ["ARR_DELAY", "ARR_DELAY_NEW", "ARR_DEL15", "ARR_ON_TIME"]

In [52]:
df.pivot_table(index ='OP_CARRIER', aggfunc = 'mean', values = perf_cols).sort_values(by=['ARR_ON_TIME'])

            ARR_DEL15  ARR_DELAY  ARR_DELAY_NEW  ARR_ON_TIME
OP_CARRIER
G4           0.232685  10.188327      17.134630     0.744151
F9           0.233766   6.129870      17.987013     0.746835
AS           0.225914   3.551495      10.724252     0.756494
NK           0.207804   8.249177      17.894217     0.764172
MQ           0.184175   1.642565      13.557981     0.804845
WN           0.158296  -0.748885       9.108217     0.828353
OO           0.155587   4.819425      15.141914     0.829935
B6           0.156934   3.408759      14.182482     0.832432
OH           0.152370   2.193002      13.138826     0.839106
YV           0.133261   0.472373      14.645720     0.842993
AA           0.121626  -2.639675      11.132033     0.860191
UA           0.118098  -1.454755       8.874233     0.873197
YX           0.095331  -4.721579       6.451876     0.893294
9E           0.095794  -3.261682      10.795561     0.901048
DL           0.067299  -5.345972       5.573934     0.928740

**Task 4.4**: Based on the above analysis, which airline is doing better Southwest (WN) or American Airlines (AA)? Which regional airline is doing better Replublic (YX) or Delta (DL)?

**Task 4.5**: Examine if these statistics are comparable by looking at patterns *where* airlines fly. Cross tabulate the destination that each carrier serves from PIT. Hint: use pd.cross_tab

### Section 5: Causes of Delay

**Task 5.1**: What are the most commonly cited reasons for flight delays by the airlines?

In [53]:
delay_cause_cols = ["CARRIER_DELAY", "WEATHER_DELAY", "NAS_DELAY", 
                    "SECURITY_DELAY", "LATE_AIRCRAFT_DELAY"]

In [54]:
df[delay_cause_cols].sum()

CARRIER_DELAY          109273.0
WEATHER_DELAY           21687.0
NAS_DELAY               61347.0
SECURITY_DELAY            781.0
LATE_AIRCRAFT_DELAY    108638.0
dtype: float64

### Optional Section 6: (Open Ended) Ask yourself a question, not asked above, that you find interesting and answer it.

---
## END