#### Carnegie Mellon University - Tepper School of Business
#### 46-881 - Programming in R and Python
#### 22/23 - Mini 2 - Sections MO2 - Farahat

## Python Review Questions - SOLUTIONS
---

### 1. Library / package management

1.1. How can you check if your Anaconda installtion has a given library / package installed? How can you check, for example, if teh popular machine learning package scikit-learn is already installed?

1. Go to Anaconda Navigator
2. Select the "Environments" tab on the left
3. Select "installed" from the drop-down menu
4. Search for the library / package by typing its name in the search box

Note: scikit-learn is already installed.

1.2. Import the numpy and pandas libraries. Make sure to use the standard abbreviations.

In [1]:
import numpy as np
import pandas as pd

### 2. Math

2.1. What number does the following expression evaluate to? Evaluate it in your head first then evaluate it using Python. 
8 / 2 * (2 + 2)  
(See https://www.nytimes.com/2019/08/02/science/math-equation-pedmas-bemdas-bedmas.html?smid=url-share)

In [2]:
8 / 2 * (2 + 2)

16.0

2.2. Write an expression that calculates 9 squared (use the power operator, not simply 9*9).

In [3]:
9**2
# you can also use:
# pow(9, 2)

81

2.3. Write an expression that calculates the square root of 9.

In [4]:
# need numpy or math library
np.sqrt(9)
# you can also use:
# math.sqrt(9)

3.0

2.4. Set a variable, x, to the value of the expression 8 / 2 * (2 + 2).

In [5]:
x = 8 / 2 * (2 + 2)

2.5. Set another variable, y, to the value of the expression 8 / (2 * (2 + 2)).

In [6]:
y = 8 / (2 * (2 + 2))

2.6. Write a logical expression that return True if the value of x is equal to the value of y, and False otherwise.

In [7]:
x == y

False

2.7. Round the floating number 3.14159 to 2 decimal places. Print the result.

In [8]:
print(round(3.14159,2))

3.14

### 3. Random number generation

References:
- Asychronous content: Week 3 - Segment 5
- numpy docs: https://numpy.org/doc/stable/reference/random/generator.html

3.1. Generate 10 random numbers drawn from a uniform distribution between 0 and 1.

In [9]:
rng = np.random.default_rng()
rng.uniform(low=0, high=1, size=10)
# low=0 and high=1 are the default values so they can be dropped:
# rng.uniform(size=10)

array([0.78523631, 0.6569393 , 0.30587183, 0.85599059, 0.77879349,
       0.41289798, 0.42329179, 0.74050015, 0.85181195, 0.53173547])

3.2. Generate 10 random numbers drawn from a normal distribution with mean = 10 and standard deviation = 3. Set the random seed to 123.

In [10]:
rng = np.random.default_rng(seed=123)
rng.normal(loc=10,scale=3,size=10)
# loc (mean) and scale (standard deviation) are positional arguments so their names can be dropped:
# rng.normal(10, 3, size=10)

array([ 7.03263595,  8.89664005, 13.86377578, 10.58192326, 12.7606927 ,
       11.73131137,  8.09060906, 11.62585666,  9.05021365,  9.03283265])

3.3 Generate 10 random numbers drawn from a binomial distribution with number of trials = 20 and success probablity = 0.5.

In [11]:
rng = np.random.default_rng(seed=123)
rng.binomial(n=20, p=0.5, size=10)

array([11,  6,  8,  8,  8, 12, 13,  9, 12, 13], dtype=int64)

3.4 Simulate the outcome of 10 random throws of a fair 6-sided die.

In [12]:
rng = np.random.default_rng(seed=123)
rng.integers(low=1, high=7, size=10)

array([1, 5, 4, 1, 6, 2, 2, 2, 3, 2], dtype=int64)

### 4. Lists

References:
- Asynchronous content: Week 3 - Segment 7; Week 4 - Segment 1
- python docs tutorial: https://docs.python.org/3/tutorial/datastructures.html#more-on-lists

4.1. Create a list of the first 7 numbers of the Fibonacci sequence: 0, 1, 1, 2, 3, 5, 8, ...

In [13]:
fib = [0, 1, 1, 2, 3, 5, 8]

4.2. Add to the end of the list the 8th number of the Fibonacci sequence, 13.

In [14]:
fib.append(13)
print(fib)

[0, 1, 1, 2, 3, 5, 8, 13]

4.3. Write a statement that prints the length of the list created above.

In [15]:
print(len(fib))

8

4.4 Retrieve the 5th number of the Fibonnaci sequence list.

In [16]:
fib[4]

3

4.5. Retrieve, as a list, the 5th to 8th numbers of the Fibonnaci sequence list.

In [17]:
fib[4:8]
# or in this case:
# fib[4:]

[3, 5, 8, 13]

4.6. Create a list of the names of the 4 teams that reached the FIFA 2022 World cup semi-finals: Croatia, Argentina, Morocco, and France (in this order, which is order in which they have reach the semi-finals stage).

In [18]:
teams = ["Croatia", "Argentina", "Morocco", "France"]

4.7. Sort the list of team names in alphabetical order

In [19]:
teams.sort()
print(teams)

['Argentina', 'Croatia', 'France', 'Morocco']

4.8. Create an independent (deep copy) of the list of teams.

In [20]:
import copy
teams2 = copy.deepcopy(teams)

4.9. Suppose Argentina and France reach the finals. Modify the list copy above by deleting Croatia and Morocco from the list.

In [21]:
teams2.remove("Croatia")
teams2.remove("Morocco")
print(teams2)

['Argentina', 'France']

4.10. Create an empty list

In [22]:
empty_list = list()

4.11. Create a list of all integers from 1 to 100 (inclusive).

In [23]:
list_from_range = list(range(1,101))
print(list_from_range)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

### 5. Dictionaries

References:
- Asychronous content: Week 4 - Segment 5
- python docs tutorial: https://docs.python.org/3/tutorial/datastructures.html#dictionaries

5.1. Create a dictionary with the FIFA point ratings of the following soccer teams: Croatia (CRO), Argentina (ARG), Morocco (MAR), and France (FRA). The point ratings of these teams (as of October 2022) are, respectively, 1645.64, 1772.88, 1563.5, and 1759.78. Use the three letter team abbreviations as dictionary keys.

In [24]:
dict1 = {"CRO": 1645.64, "ARG": 1772.88, "MAR": 1563.5, "FRA": 1759.78}

5.2. Write a statement that retrieves the point rating of Morocco.

In [25]:
dict1["MAR"]

1563.5

5.3. Write a statement that prints the length of the dictionary created above.

In [26]:
print(len(dict1))

4

5.4. Write an expression that calculates the average point rating of the 4 teams in the dictionary created above.

In [27]:
sum(list(dict1.values())) / len(dict1)

1685.45

### 6. User-defined functions

References:
- Asynchronous content: Week 4 - Segment 3
- python docs tutorial: https://docs.python.org/3/tutorial/controlflow.html#defining-functions

6.1. Define a function that sums the squares of the elements of any list. Test it on this list [0, 1, 1, 2, 3]

In [28]:
def fun2(list_input):
    list_squared = [x**2 for x in list_input]
    sum_squares = sum(list_squared)
    return(sum_squares)

In [29]:
fun2([0, 1, 1, 2, 3])

15

6.2. Define a function that takes two equal-length lists, a list of predicted numerical values and a list of actual numerical values, and calculates the root mean square error (or deviation) between these two lists. For example, if pred = [1.5, 2.0, 2.5] and actual = [1, 2, 3]  then the root means square error is: 
$$\sqrt{\frac{(1.5-1)^{2}+(2.0-2)^{2}+(2.5-3)^{2}}{3}} = 0.408 $$

In [30]:
def rmse(pred, actual):
    error = np.subtract(pred, actual)
    mean_square_error = fun2(error) / len(error)
    return(np.sqrt(mean_square_error))

In [31]:
# Test
rmse([1.5, 2.0, 2.5], [1, 2, 3])

0.408248290463863

### 7. Conditional (if-else) statements

References:
- Asynchronous content: Week 3 - Segment 3
- python docs tutorial: https://docs.python.org/3/tutorial/controlflow.html#if-statements

7.1. Write a function that returns True if a number is even and False if it is odd. Hint: Try using the modulo "%" operator; e.g. 4 % 2 evaluates to 0 while 5 % 2 evaluates to 1.

In [32]:
def even_fun(num):
    if (num % 2) == 0:
        return(True)
    else:
        return(False)

In [33]:
# Test 
even_fun(5)

False

7.2. Write a function that takes the score of two teams: Team A and Team B and returns "A" if Team A won, "B" if Team B won, and "Draw" if the outcome was a draw.

In [34]:
def result_fun(A_score, B_score):
    if A_score > B_score:
        return("A")
    elif A_score < B_score:
        return("B")
    else:
        return("Draw")

In [35]:
#Test 
result_fun(1,3)

'B'

### 8. Loops (for statements)

References:
- Asynchronous content: Week 3 - Segment 6
- Python docs tutorial: https://docs.python.org/3/tutorial/controlflow.html#for-statements

8.1. Use a for loop to print the squares of the integers 1 through 9 (i.e. print 1, 4, ..., 81).

In [36]:
for i in range(1,10):
    print(i**2)

1
4
9
16
25
36
49
64
81

8.2. Use a for loop to print the parity (i.e. "even"/"odd") of each number in this list of Fibonnaci numbers: [0,1,1,2,3,5,8,13].

In [37]:
fib_list = [0,1,1,2,3,5,8,13]
for num in fib_list:
    if (num % 2) == 0:
        print("even")
    else:
        print("odd")

even
odd
odd
even
odd
odd
even
odd

8.3. Use a for loop to calculate the sum of the first 100 integers (1 through 100)

In [38]:
sum_val = 0
for i in range(1,101):
    sum_val = sum_val + i
print(sum_val)

5050

### 9. pandas data frames

References:
- Asynchronous content: Week 5
- Python for Data Science, 3rd ed: https://wesmckinney.com/book/pandas-basics.html

9.1. Read in the data file <simplified_airline_data.csv> as a pandas dataframe.

In [39]:
df = pd.read_csv("simplified_airline_data.csv")

9.2. List the column names of the dataframe

In [40]:
list(df.columns)

['Flight number',
 'Airline',
 'Origin airport',
 'Destination airport',
 'Date',
 'Scheduled departure time',
 'Scheduled arrival time',
 'Actual arrival time',
 'Arrival delay minutes',
 'Week day',
 'Route code']

9.3. Retrieve the rows of the dataframe where "Actual arrival time" is set to "Cancelled".

In [41]:
df[df["Actual arrival time"] == "Cancelled"]

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code
249,QU3322,Quanta,DCA,PIT,8/2/2018,6:35,8:15,Cancelled,NaN,Wed,DCA_PIT
264,QU3322,Quanta,DCA,PIT,8/17/2018,6:35,8:15,Cancelled,NaN,Fri,DCA_PIT
292,QU4422,Quanta,LGA,PIT,8/14/2018,21:55,23:20,Cancelled,NaN,Tue,LGA_PIT
293,QU4422,Quanta,LGA,PIT,8/15/2018,21:55,23:20,Cancelled,NaN,Wed,LGA_PIT
296,QU4422,Quanta,LGA,PIT,8/18/2018,21:55,23:20,Cancelled,NaN,Sat,LGA_PIT
299,QU4422,Quanta,LGA,PIT,8/21/2018,21:55,23:20,Cancelled,NaN,Tue,LGA_PIT
306,QU4422,Quanta,LGA,PIT,8/28/2018,21:55,23:20,Cancelled,NaN,Tue,LGA_PIT
325,QU5515,Quanta,PIT,DCA,8/16/2018,20:20,22:00,Cancelled,NaN,Thu,PIT_DCA
328,QU5515,Quanta,PIT,DCA,8/19/2018,20:20,22:00,Cancelled,NaN,Sun,PIT_DCA
329,QU5515,Quanta,PIT,DCA,8/20/2018,20:20,22:00,Cancelled,NaN,Mon,PIT_DCA
354,QU5520,Quanta,PIT,LGA,8/14/2018,13:35,15:00,Cancelled,NaN,Tue,PIT_LGA
364,QU5520,Quanta,PIT,LGA,8/24/2018,13:35,15:00,Cancelled,NaN,Fri,PIT_LGA

9.4. Create a new column in the dataframe, labelled "new_arr_del", and set it equal to the absolute value of "Arrival delay minutes" (that is, negative values are set to zero). Hint: apply the abs function.

In [42]:
import numpy as np
df["new_arr_del"] = df["Arrival delay minutes"].apply(abs)
df

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code,new_arr_del
0,OP3425,Optima,DCA,PIT,8/1/2018,18:05,19:35,19:51,16.0,Wed,DCA_PIT,16.0
1,OP3425,Optima,DCA,PIT,8/2/2018,18:05,19:35,19:50,15.0,Thu,DCA_PIT,15.0
2,OP3425,Optima,DCA,PIT,8/3/2018,18:05,19:35,19:39,4.0,Fri,DCA_PIT,4.0
3,OP3425,Optima,DCA,PIT,8/4/2018,18:05,19:35,19:49,14.0,Sat,DCA_PIT,14.0
4,OP3425,Optima,DCA,PIT,8/5/2018,18:05,19:35,19:37,2.0,Sun,DCA_PIT,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
367,QU5520,Quanta,PIT,LGA,8/27/2018,13:35,15:00,14:59,-1.0,Mon,PIT_LGA,1.0
368,QU5520,Quanta,PIT,LGA,8/28/2018,13:35,15:00,15:17,17.0,Tue,PIT_LGA,17.0
369,QU5520,Quanta,PIT,LGA,8/29/2018,13:35,15:00,15:34,34.0,Wed,PIT_LGA,34.0
370,QU5520,Quanta,PIT,LGA,8/30/2018,13:35,15:00,15:24,24.0,Thu,PIT_LGA,24.0
371,QU5520,Quanta,PIT,LGA,8/31/2018,13:35,15:00,15:15,15.0,Fri,PIT_LGA,15.0

9.5. Create a new column in the dataframe, labelled "null_col", and set all of its entries to NaN.

In [43]:
df["null_col"] = np.nan
df

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code,new_arr_del,null_col
0,OP3425,Optima,DCA,PIT,8/1/2018,18:05,19:35,19:51,16.0,Wed,DCA_PIT,16.0,NaN
1,OP3425,Optima,DCA,PIT,8/2/2018,18:05,19:35,19:50,15.0,Thu,DCA_PIT,15.0,NaN
2,OP3425,Optima,DCA,PIT,8/3/2018,18:05,19:35,19:39,4.0,Fri,DCA_PIT,4.0,NaN
3,OP3425,Optima,DCA,PIT,8/4/2018,18:05,19:35,19:49,14.0,Sat,DCA_PIT,14.0,NaN
4,OP3425,Optima,DCA,PIT,8/5/2018,18:05,19:35,19:37,2.0,Sun,DCA_PIT,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,QU5520,Quanta,PIT,LGA,8/27/2018,13:35,15:00,14:59,-1.0,Mon,PIT_LGA,1.0,NaN
368,QU5520,Quanta,PIT,LGA,8/28/2018,13:35,15:00,15:17,17.0,Tue,PIT_LGA,17.0,NaN
369,QU5520,Quanta,PIT,LGA,8/29/2018,13:35,15:00,15:34,34.0,Wed,PIT_LGA,34.0,NaN
370,QU5520,Quanta,PIT,LGA,8/30/2018,13:35,15:00,15:24,24.0,Thu,PIT_LGA,24.0,NaN
371,QU5520,Quanta,PIT,LGA,8/31/2018,13:35,15:00,15:15,15.0,Fri,PIT_LGA,15.0,NaN

9.6. Delete the column labelled "null_col".

In [44]:
df.drop("null_col",axis="columns")

,Flight number,Airline,Origin airport,Destination airport,Date,Scheduled departure time,Scheduled arrival time,Actual arrival time,Arrival delay minutes,Week day,Route code,new_arr_del
0,OP3425,Optima,DCA,PIT,8/1/2018,18:05,19:35,19:51,16.0,Wed,DCA_PIT,16.0
1,OP3425,Optima,DCA,PIT,8/2/2018,18:05,19:35,19:50,15.0,Thu,DCA_PIT,15.0
2,OP3425,Optima,DCA,PIT,8/3/2018,18:05,19:35,19:39,4.0,Fri,DCA_PIT,4.0
3,OP3425,Optima,DCA,PIT,8/4/2018,18:05,19:35,19:49,14.0,Sat,DCA_PIT,14.0
4,OP3425,Optima,DCA,PIT,8/5/2018,18:05,19:35,19:37,2.0,Sun,DCA_PIT,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
367,QU5520,Quanta,PIT,LGA,8/27/2018,13:35,15:00,14:59,-1.0,Mon,PIT_LGA,1.0
368,QU5520,Quanta,PIT,LGA,8/28/2018,13:35,15:00,15:17,17.0,Tue,PIT_LGA,17.0
369,QU5520,Quanta,PIT,LGA,8/29/2018,13:35,15:00,15:34,34.0,Wed,PIT_LGA,34.0
370,QU5520,Quanta,PIT,LGA,8/30/2018,13:35,15:00,15:24,24.0,Thu,PIT_LGA,24.0
371,QU5520,Quanta,PIT,LGA,8/31/2018,13:35,15:00,15:15,15.0,Fri,PIT_LGA,15.0

### 10. pandas pivot tables

References:
- Asynchronous content: Week 6 - Segment 1
- Python for Data Science, 3rd ed: https://wesmckinney.com/book/data-aggregation.html#groupby_pivot_table

Re-read in the data file <simplified_airline_data.csv> as a pandas dataframe and perform the following pivot table analyses:

In [45]:
df = pd.read_csv("simplified_airline_data.csv")

10.1. Create a pivot table of mean "Arrival delay minutes" aggregated by "Airline" (as rows) and "Route code" (as columns).

In [46]:
df.pivot_table(index=["Airline"], columns=["Route code"], aggfunc = "mean", values=["Arrival delay minutes"])

           Arrival delay minutes
Route code               DCA_PIT    LGA_PIT   PIT_DCA    PIT_LGA
Airline
Optima                  7.419355  16.526882  8.290323  17.473118
Quanta                  6.827586  19.230769  8.250000  17.206897

10.2. Create a pivot table of mean "Arrival delay minutes" aggregated by "Airline" (as rows) and "Week day" (as columns). Include margin values.

In [47]:
df.pivot_table(index=["Airline"], columns=["Week day"], aggfunc = "mean", values=["Arrival delay minutes"], margins=True)

         Arrival delay minutes                                              \
Week day                   Fri        Mon        Sat        Sun        Thu
Airline
Optima               13.175000  18.281250  15.750000  15.812500  14.450000
Quanta               10.388889  14.133333  10.866667  11.666667  15.111111
All                  12.310345  16.957447  14.191489  14.489362  14.655172


Week day        Tue        Wed        All
Airline
Optima    12.031250  14.100000  14.713710
Quanta    12.666667  14.052632  12.750000
All       12.204545  14.084746  14.102778

10.3. Create a pivot table of the count of flights aggregated by "Airline" and "Route code" (as rows) and "Week day" (as columns.

In [48]:
df.pivot_table(index=["Airline", "Route code"], columns=["Week day"], aggfunc = "count", values=["Flight number"], margins=True)

                   Flight number
Week day                     Fri Mon Sat Sun Thu Tue Wed  All
Airline Route code
Optima  DCA_PIT                5   4   4   4   5   4   5   31
        LGA_PIT               15  12  12  12  15  12  15   93
        PIT_DCA                5   4   4   4   5   4   5   31
        PIT_LGA               15  12  12  12  15  12  15   93
Quanta  DCA_PIT                5   4   4   4   4   4   6   31
        LGA_PIT                5   4   4   4   5   4   5   31
        PIT_DCA                5   4   4   4   5   4   5   31
        PIT_LGA                5   4   4   4   5   4   5   31
All                           60  48  48  48  59  48  61  372

---
### END