-  0 denotes good risk (i.e. accept and issue load).
-  1 denotes bad risk (i.e. decline)

## Setting up

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
#conda update anaconda

In [48]:
#conda install -c anaconda graphviz

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_graphviz
from graphviz import Source

In [50]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [51]:
pd.options.display.max_columns = None

In [52]:
def plot_roc_curve(fpr, tpr, label=None):
    plt.plot(fpr, tpr, linewidth=2, label=label)
    plt.plot([0,1],[0,1], 'k--')
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")

## Importing data

In [59]:
df = pd.read_csv("bank_lrmodeltrain.csv")

In [60]:
df = df.drop(['Unnamed: 0'], axis=1)

In [61]:
df

,age,balance,campaign,contact,day,default,duration,education,housing,job,loan,marital,month,pdays,poutcome,previous,y
0,58,2143,1,unknown,5,no,261,tertiary,yes,management,no,married,may,-1,unknown,0,no
1,44,29,1,unknown,5,no,151,secondary,yes,technician,no,single,may,-1,unknown,0,no
2,33,2,1,unknown,5,no,76,secondary,yes,entrepreneur,yes,married,may,-1,unknown,0,no
3,47,1506,1,unknown,5,no,92,unknown,yes,blue-collar,no,married,may,-1,unknown,0,no
4,33,1,1,unknown,5,no,198,unknown,no,unknown,no,single,may,-1,unknown,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27081,23,113,1,cellular,17,no,266,tertiary,no,student,no,single,nov,-1,unknown,0,yes
27082,25,505,2,cellular,17,no,386,secondary,no,technician,yes,single,nov,-1,unknown,0,yes
27083,51,825,3,cellular,17,no,977,tertiary,no,technician,no,married,nov,-1,unknown,0,yes
27084,72,5715,5,cellular,17,no,1127,secondary,no,retired,no,married,nov,184,success,3,yes
27085,37,2971,2,cellular,17,no,361,secondary,no,entrepreneur,no,married,nov,188,other,11,no

## Train / Test split

In [62]:
y = df["y"]
X = df.drop("y", axis=1)

In [63]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=886)

In [64]:
X

,age,balance,campaign,contact,day,default,duration,education,housing,job,loan,marital,month,pdays,poutcome,previous
0,58,2143,1,unknown,5,no,261,tertiary,yes,management,no,married,may,-1,unknown,0
1,44,29,1,unknown,5,no,151,secondary,yes,technician,no,single,may,-1,unknown,0
2,33,2,1,unknown,5,no,76,secondary,yes,entrepreneur,yes,married,may,-1,unknown,0
3,47,1506,1,unknown,5,no,92,unknown,yes,blue-collar,no,married,may,-1,unknown,0
4,33,1,1,unknown,5,no,198,unknown,no,unknown,no,single,may,-1,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27081,23,113,1,cellular,17,no,266,tertiary,no,student,no,single,nov,-1,unknown,0
27082,25,505,2,cellular,17,no,386,secondary,no,technician,yes,single,nov,-1,unknown,0
27083,51,825,3,cellular,17,no,977,tertiary,no,technician,no,married,nov,-1,unknown,0
27084,72,5715,5,cellular,17,no,1127,secondary,no,retired,no,married,nov,184,success,3
27085,37,2971,2,cellular,17,no,361,secondary,no,entrepreneur,no,married,nov,188,other,11

In [65]:
y

0         no
1         no
2         no
3         no
4         no
        ...
27081    yes
27082    yes
27083    yes
27084    yes
27085     no
Name: y, Length: 27086, dtype: object

In [66]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
import os

In [67]:
log_reg = LogisticRegression()
log_reg.fit(X,y)

ValueError: could not convert string to float: 'unknown'