## **Manipulating DataFrames**
- This notebook provides some practice on manipulating Dataframes

### **Exercises**
- Import BP stock price data from January 1, 2004 to December 31, 2019 and save it in a variable named df_BP
- Obtain info on df_BP, specifically what is it's type and shape?
- What does the index of df_BP contain? Similarly, ascertain the columns of df_BP.
- Assign the fifth column of df_BP to the variable named volume, what is the type of volume?
- Print volume.values and ascertain the type of these values
- Print the first and last three rows of BP?
- Create a new column called Mkt Cap and assign it the value 0
- Replace every third value of Mkt Cap with the number 1000

### **Exercises**
- Using BP's Adj Close and High prices, create two new dataframe, df1 and df2
    - join both dataframes
    - concatenate both setting axis = rows
    - note the difference.
- print the BP data for 19 February, 2019
- print only the High and Low price for 19 February, 2019
- print only the High and Low price for all of February, 2019
- resample BP data every month, and obtain the last price.

In [4]:
from pandas_datareader.data import DataReader
from datetime import date, datetime, timedelta
import pandas as pd
import numpy as np

In [6]:
ticker = 'BP'
source = 'yahoo'
end_date = date(2019,12,31)
begin_date = date(2004,1,1)
#df_BP = DataReader(ticker, source,  begin_date, end_date)
from pandas_datareader import data as DataReader
import yfinance as yf
yf.pdr_override()
df_BP = DataReader.get_data_yahoo(ticker, start=begin_date, end=end_date)

#df_BP.to_csv('data/df_BP.csv') 

#df_BP = pd.read_csv('data/df_BP.csv', parse_dates=['Date'], index_col='Date')

[*********************100%***********************]  1 of 1 completed

In [4]:
print(type(df_BP))
print(df_BP.shape)
print(df_BP.info())

<class 'pandas.core.frame.DataFrame'>
(4026, 6)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4026 entries, 2004-01-02 to 2019-12-30
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       4026 non-null   float64
 1   High       4026 non-null   float64
 2   Low        4026 non-null   float64
 3   Close      4026 non-null   float64
 4   Adj Close  4026 non-null   float64
 5   Volume     4026 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 220.2 KB
None

In [5]:
print(df_BP.index)
print(df_BP.columns)

DatetimeIndex(['2004-01-02', '2004-01-05', '2004-01-06', '2004-01-07',
               '2004-01-08', '2004-01-09', '2004-01-12', '2004-01-13',
               '2004-01-14', '2004-01-15',
               ...
               '2019-12-16', '2019-12-17', '2019-12-18', '2019-12-19',
               '2019-12-20', '2019-12-23', '2019-12-24', '2019-12-26',
               '2019-12-27', '2019-12-30'],
              dtype='datetime64[ns]', name='Date', length=4026, freq=None)
Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [6]:
volume = df_BP['Volume']
type(volume)

pandas.core.series.Series

In [7]:
print(volume.values)
type(volume.values)

[2972500 4142800 3172900 ... 4504200 5436600 6105900]

numpy.ndarray

In [8]:
print(df_BP.head())
print(df_BP.tail(3))

                 Open       High        Low      Close  Adj Close   Volume
Date
2004-01-02  49.529999  49.599998  49.200001  49.400002  20.014423  2972500
2004-01-05  49.349998  50.049999  49.310001  49.900002  20.217007  4142800
2004-01-06  50.090000  50.400002  49.959999  50.220001  20.346651  3172900
2004-01-07  49.130001  49.150002  48.750000  49.020000  19.860470  5830200
2004-01-08  49.200001  49.340000  48.930000  49.070000  19.880724  2941100
                 Open       High        Low      Close  Adj Close   Volume
Date
2019-12-26  38.060001  38.200001  37.939999  37.980000  33.481689  4504200
2019-12-27  38.240002  38.250000  37.860001  37.860001  33.375904  5436600
2019-12-30  37.799999  37.970001  37.570000  37.599998  33.146694  6105900

In [9]:
print(df_BP.iloc[0:3,:])
print(df_BP.iloc[-3:,:])

                 Open       High        Low      Close  Adj Close   Volume
Date
2004-01-02  49.529999  49.599998  49.200001  49.400002  20.014423  2972500
2004-01-05  49.349998  50.049999  49.310001  49.900002  20.217007  4142800
2004-01-06  50.090000  50.400002  49.959999  50.220001  20.346651  3172900
                 Open       High        Low      Close  Adj Close   Volume
Date
2019-12-26  38.060001  38.200001  37.939999  37.980000  33.481689  4504200
2019-12-27  38.240002  38.250000  37.860001  37.860001  33.375904  5436600
2019-12-30  37.799999  37.970001  37.570000  37.599998  33.146694  6105900

In [10]:
df_BP['MKTCap'] = 0 # Broadcasts to entire column
df_BP['MKTCap'][::3] = 1000 # here the step size is 3 
df_BP.head(5)

C:\Users\zkhok\anaconda3\envs\env_base_SS\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\zkhok\anaconda3\envs\env_base_SS\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

,Open,High,Low,Close,Adj Close,Volume,MKTCap
Date,,,,,,,
2004-01-02,49.529999,49.599998,49.200001,49.400002,20.014423,2972500,1000
2004-01-05,49.349998,50.049999,49.310001,49.900002,20.217007,4142800,0
2004-01-06,50.090000,50.400002,49.959999,50.220001,20.346651,3172900,0
2004-01-07,49.130001,49.150002,48.750000,49.020000,19.860470,5830200,1000
2004-01-08,49.200001,49.340000,48.930000,49.070000,19.880724,2941100,0

In [11]:
df1 = df_BP['Adj Close'].to_frame()
df2 = df_BP['High'].to_frame()
df4 = df2.join(df1)
df3 = pd.concat([df2, df1], axis='rows')
print(df3)
print(df4)

                 High  Adj Close
Date
2004-01-02  49.599998        NaN
2004-01-05  50.049999        NaN
2004-01-06  50.400002        NaN
2004-01-07  49.150002        NaN
2004-01-08  49.340000        NaN
...               ...        ...
2019-12-23        NaN  33.596291
2019-12-24        NaN  33.534580
2019-12-26        NaN  33.481689
2019-12-27        NaN  33.375904
2019-12-30        NaN  33.146694

[8052 rows x 2 columns]
                 High  Adj Close
Date
2004-01-02  49.599998  20.014423
2004-01-05  50.049999  20.217007
2004-01-06  50.400002  20.346651
2004-01-07  49.150002  19.860470
2004-01-08  49.340000  19.880724
...               ...        ...
2019-12-23  38.119999  33.596291
2019-12-24  38.139999  33.534580
2019-12-26  38.200001  33.481689
2019-12-27  38.250000  33.375904
2019-12-30  37.970001  33.146694

[4026 rows x 2 columns]

In [12]:
df_BP.loc['2019-02-19']
df_BP.loc['2019-02-19',['High','Low']]
df_BP.loc['2019-02',['High','Low']]
df_BP.loc['2019-02':'2019-03',['High','Low']]

                 High        Low
Date
2019-02-01  41.400002  40.980000
2019-02-04  41.410000  40.860001
2019-02-05  42.889999  42.520000
2019-02-06  43.410000  43.040001
2019-02-07  43.259998  42.450001
2019-02-08  42.500000  42.150002
2019-02-11  42.320000  42.060001
2019-02-12  42.639999  42.330002
2019-02-13  42.849998  42.549999
2019-02-14  42.070000  41.669998
2019-02-15  42.360001  42.080002
2019-02-19  42.490002  41.889999
2019-02-20  42.740002  42.380001
2019-02-21  42.419998  42.139999
2019-02-22  42.540001  42.209999
2019-02-25  42.680000  42.349998
2019-02-26  42.689999  42.310001
2019-02-27  43.020000  42.689999
2019-02-28  42.849998  42.599998
2019-03-01  42.779999  42.389999
2019-03-04  42.750000  42.310001
2019-03-05  42.759998  42.580002
2019-03-06  42.790001  42.529999
2019-03-07  42.779999  42.490002
2019-03-08  42.279999  41.840000
2019-03-11  42.400002  42.180000
2019-03-12  42.610001  42.130001
2019-03-13  43.950001  43.040001
2019-03-14  44.270000  43.869999
2019-03-15  44.040001  43.750000
2019-03-18  44.310001  43.919998
2019-03-19  44.970001  44.380001
2019-03-20  44.750000  44.020000
2019-03-21  44.669998  44.310001
2019-03-22  44.250000  43.689999
2019-03-25  43.900002  43.349998
2019-03-26  44.290001  43.680000
2019-03-27  43.810001  43.200001
2019-03-28  43.709999  43.349998
2019-03-29  44.080002  43.520000

In [13]:
df_BP_monthly = df_BP.resample('M').last()
df_BP_monthly.head()

,Open,High,Low,Close,Adj Close,Volume,MKTCap
Date,,,,,,,
2004-01-31,47.730000,47.910000,47.490002,47.599998,19.285152,2972300,0
2004-02-29,49.299999,49.410000,48.820000,49.200001,20.119228,3004700,0
2004-03-31,51.259998,51.400002,50.520000,51.200001,20.937080,3716900,0
2004-04-30,52.500000,53.029999,52.369999,52.900002,21.632250,3329100,0
2004-05-31,53.299999,53.369999,52.750000,53.000000,21.841164,2673000,1000