## 46-881 Class 5

### Python pandas: Data Exploration and Wrangling (Part 1)

Amr Farahat

CMU / Tepper

2022-11-25

---

## Python pandas: Data structures

In [2]:
import numpy as np
import pandas as pd

#### The pandas Series

A pandas Series is a **one-dimensional** array(-like) object consisting of values **of the same data type** along with an associated array of (row) labels called the **index**.

Suppose we have two stores generating revenue in Q1. We can create a Series from a python list using the Series function. For example:

In [3]:
Q1_revenue = pd.Series([1000, 2500])
print(Q1_revenue)

0    1000
1    2500
dtype: int64

In [4]:
Q1_revenue.index

RangeIndex(start=0, stop=2, step=1)

We can specify a custom index:

In [5]:
Q1_revenue = pd.Series([1000, 2500],
                       index=["store A", "store B"])
print(Q1_revenue)

store A    1000
store B    2500
dtype: int64

Series elements are accessible by their indices:

In [6]:
print(Q1_revenue["store B"])

2500

Indices are preserved during arithmetic operations:

In [7]:
Q1_revenue_after_tax = 0.7 * Q1_revenue
print(Q1_revenue_after_tax)

store A     700.0
store B    1750.0
dtype: float64

Indices are also preserved during filtering operations:

In [8]:
Q1_revenue[Q1_revenue > 1000]

store B    2500
dtype: int64

In [9]:
Q1_revenue

store A    1000
store B    2500
dtype: int64

We can also create a pandas Series from a Python dictionary using the Series function. For example:

In [10]:
Q2_revenue = pd.Series({"store C": 500, "store A": 1300, "store B": 2900})
print(Q2_revenue)

store C     500
store A    1300
store B    2900
dtype: int64

Indices align data rows properly. For example:

In [11]:
cumulative_revenue = Q1_revenue + Q2_revenue
print(cumulative_revenue)

store A    2300.0
store B    5400.0
store C       NaN
dtype: float64

The index object can be retrieved using the index attribute of a series:

In [13]:
print(list(cumulative_revenue.index))

['store A', 'store B', 'store C']

In [14]:
cumulative_revenue.index

Index(['store A', 'store B', 'store C'], dtype='object')

#### The pandas DataFrame

A pandas DataFrame is a **rectangular** data structure consisting of multiple columns. Each column has a specific data type, but **the data types can vary across columns**.

You can think of a pandas DataFrame as a dictionary of pandas Series, all **sharing the same index**.

In [16]:
Q1_revenue

store A    1000
store B    2500
dtype: int64

In [17]:
Q2_revenue

store C     500
store A    1300
store B    2900
dtype: int64

In [18]:
revenue_df = pd.DataFrame({"Q1": Q1_revenue, "Q2": Q2_revenue})
print(revenue_df)

             Q1    Q2
store A  1000.0  1300
store B  2500.0  2900
store C     NaN   500

You can create a DataFrame directly from a dictionary of equal-length lists.

In [19]:
Q2_df = pd.DataFrame({"revenue": [500, 1300, 2900],
                      "costs": [200, 500, 700]},
                      index = ["store C", "store A", "store B"])
print(Q2_df)

         revenue  costs
store C      500    200
store A     1300    500
store B     2900    700

#### Retrieving row indices and column names

In [20]:
print(Q2_df.index)

Index(['store C', 'store A', 'store B'], dtype='object')

In [21]:
print(list(Q2_df.columns))

['revenue', 'costs']

#### Browser display

In [22]:
Q2_df

         revenue  costs
store C      500    200
store A     1300    500
store B     2900    700

#### Pointers vs. Copies

In [23]:
df1 = Q2_df

In [24]:
df1

         revenue  costs
store C      500    200
store A     1300    500
store B     2900    700

In [25]:
df1["profit"] = df1["revenue"] - df1["costs"]

In [26]:
df1

         revenue  costs  profit
store C      500    200     300
store A     1300    500     800
store B     2900    700    2200

In [27]:
Q2_df

         revenue  costs  profit
store C      500    200     300
store A     1300    500     800
store B     2900    700    2200

*The assignment (=) copies the pointer to the location of the dataframe. It does not create a separate copy the dataframe.*

What if we want a separate copy of the dataframe?

In [28]:
Q2_df = pd.DataFrame({"revenue": [1300, 2900, 500],
                      "costs": [500, 700, 200]},
                      index = ["store A", "store B", "store C"])

In [29]:
Q2_df

         revenue  costs
store A     1300    500
store B     2900    700
store C      500    200

In [30]:
df2 = Q2_df.copy()

In [31]:
df2

         revenue  costs
store A     1300    500
store B     2900    700
store C      500    200

In [32]:
df2["profit"] = df2["revenue"] - df2["costs"]

In [33]:
df2

         revenue  costs  profit
store A     1300    500     800
store B     2900    700    2200
store C      500    200     300

In [34]:
Q2_df

         revenue  costs
store A     1300    500
store B     2900    700
store C      500    200

*Use the copy method to create a separate copy the dataframe.*

---
## END