## 46-881 Class 5

### Python pandas: Data Exploration and Wrangling (Part 1)

Amr Farahat

CMU / Tepper

2022-11-25

---

## Python pandas: Selection in DataFrames

In [12]:
import numpy as np
import pandas as pd

In [13]:
df = pd.DataFrame({"revenue": [500, 1300, 2900],
                    "costs": [200, 500, 700],
                   "profit": [300, 800, 2200]},
                    index = ["store A", "store B", "store C"])

In [14]:
df

         revenue  costs  profit
store A      500    200     300
store B     1300    500     800
store C     2900    700    2200

#### Selecting a single value by row and column label

In [16]:
df.at["store B", "costs"]

500

#### Selecting a single value by row and column integer position

In [17]:
df.iat[2, 1]

700

#### Selecting both row(s) and column(s) by label

In [18]:
df.loc[["store B", "store C"], ["revenue", "costs"]]

         revenue  costs
store B     1300    500
store C     2900    700

#### Selecting both row(s) and column(s) by integer position

In [19]:
df.iloc[[2],[0]]

         revenue
store C     2900

#### Selecting row(s) by label

In [24]:
df.loc[["store B", "store C"]]

         revenue  costs  profit
store B     1300    500     800
store C     2900    700    2200

#### Selecting row(s) by integer position

In [25]:
df

         revenue  costs  profit
store A      500    200     300
store B     1300    500     800
store C     2900    700    2200

In [26]:
df.iloc[[2,0]]

         revenue  costs  profit
store C     2900    700    2200
store A      500    200     300

#### Selecting columns(s) by label

In [31]:
df.loc[:, ["revenue","costs"]]

         revenue  costs
store A      500    200
store B     1300    500
store C     2900    700

In [32]:
df[["revenue","costs"]]

         revenue  costs
store A      500    200
store B     1300    500
store C     2900    700

#### Selecting columns(s) by integer position

In [33]:
df.iloc[:, [0,1]]

         revenue  costs
store A      500    200
store B     1300    500
store C     2900    700

---
## END