## 46-881 Class 5

### Python pandas: Data Exploration and Wrangling (Part 1)

Amr Farahat

CMU / Tepper

2022-11-25

---

## Python pandas: Importing data

In [1]:
import numpy as np
import pandas as pd

#### Introducing the PIT departures dataset

Place the accompanying dataset "PIT_2021.csv" **in the same folder location as this Notebook**. The dataset has flight delay information pertainig to all departures out of PIT (Pittsburgh International Airport) in 2021.

Data source: Bureau of Transportation Statistics.
Covers domestic flights only
https://www.transtats.bts.gov/DL_SelectFields.aspx?gnoyr_VQ=FGJ&QO_fu146_anzr=b0-gvzr

The dataset contains scheduled and actual departure and arrival times reported by certified U.S. air carriers that account for at least one percent of domestic scheduled passenger revenues. The data is collected by the Office of Airline Information, Bureau of Transportation Statistics (BTS).

Accompanying reference files "Documentation.xlsx" and "Carrier_codes.xlsx" are available on Canvas.

#### Importing csv data as a DataFrame

In [2]:
df = pd.read_csv("PIT_2021.csv")

#### Quick inspection

In [3]:
%whos

Variable   Type         Data/Info
---------------------------------
df         DataFrame           YEAR  MONTH  DAY_O<...>[32620 rows x 33 columns]
np         module       <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
pd         module       <module 'pandas' from '/o<...>ages/pandas/__init__.py'>

To find the dimensions of df

In [4]:
df.shape

(32620, 33)

*We have 32620 fights, described by 33 columns, flown out of PIT in 2021. These are all the domestic flights flown out of PIT by certified U.S. carriers with at least 1% of domestic scheduled passenger revenue.*

In [5]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32620 entries, 0 to 32619
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   YEAR                 32620 non-null  int64
 1   MONTH                32620 non-null  int64
 2   DAY_OF_MONTH         32620 non-null  int64
 3   DAY_OF_WEEK          32620 non-null  int64
 4   FL_DATE              32620 non-null  object
 5   OP_CARRIER           32620 non-null  object
 6   OP_CARRIER_FL_NUM    32620 non-null  int64
 7   ORIGIN               32620 non-null  object
 8   ORIGIN_CITY_NAME     32620 non-null  object
 9   ORIGIN_STATE_ABR     32620 non-null  object
 10  DEST                 32620 non-null  object
 11  DEST_CITY_NAME       32620 non-null  object
 12  DEST_STATE_ABR       32620 non-null  object
 13  CRS_DEP_TIME         32620 non-null  int64
 14  DEP_TIME             32177 non-null  float64
 15  DEP_DELAY            32177 non-null  float64
 16  DEP_DELAY_NEW        32177 non-null  float64
 17  DEP_DEL15            32177 non-null  float64
 18  DEP_TIME_BLK         32620 non-null  object
 19  CRS_ARR_TIME         32620 non-null  int64
 20  ARR_TIME             32161 non-null  float64
 21  ARR_DELAY            32089 non-null  float64
 22  ARR_DELAY_NEW        32089 non-null  float64
 23  ARR_DEL15            32089 non-null  float64
 24  ARR_TIME_BLK         32620 non-null  object
 25  CANCELLED            32620 non-null  float64
 26  CANCELLATION_CODE    454 non-null    object
 27  DIVERTED             32620 non-null  float64
 28  CARRIER_DELAY        4337 non-null   float64
 29  WEATHER_DELAY        4337 non-null   float64
 30  NAS_DELAY            4337 non-null   float64
 31  SECURITY_DELAY       4337 non-null   float64
 32  LATE_AIRCRAFT_DELAY  4337 non-null   float64
dtypes: float64(15), int64(7), object(11)
memory usage: 8.2+ MB

#### Viewing the DataFrame

Jupyter notebooks do not have the nice viewer functionality of RStudio :(. There are specialized packages or add-ins you can use for that but we won't cover them here.

The code cell below to disable limits on the number of columns displayed in Jupyter (so you can scroll across and inspect all columns)

In [6]:
pd.options.display.max_columns = None

Warning: Be careful not to set max_rows to None - there's enough space or memory to display the entire data frame at once.

In [7]:
df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1900.0,-1.0,0.0,0.0,1900-1959,2025,2023.0,-2.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,756.0,-4.0,0.0,0.0,0800-0859,921,904.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,754.0,-6.0,0.0,0.0,0800-0859,921,903.0,-18.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1245,1243.0,-2.0,0.0,0.0,1200-1259,1403,1339.0,-24.0,0.0,0.0,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,807.0,7.0,7.0,0.0,0800-0859,930,913.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,1639,1645.0,6.0,6.0,0.0,1600-1659,1859,1853.0,-6.0,0.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,838,833.0,-5.0,0.0,0.0,0800-0859,1022,1019.0,-3.0,0.0,0.0,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,610,604.0,-6.0,0.0,0.0,0600-0659,835,822.0,-13.0,0.0,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,1600,1704.0,64.0,64.0,1.0,1600-1659,1744,1841.0,57.0,57.0,1.0,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,EWR,"Newark, NJ",NJ,1635,1630.0,-5.0,0.0,0.0,1600-1659,1802,1812.0,10.0,10.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

Inspect the first few rows and last few rows of df. Note the default index column 0 .. length-1.

In [8]:
df.head(8)

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1900.0,-1.0,0.0,0.0,1900-1959,2025,2023.0,-2.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,756.0,-4.0,0.0,0.0,0800-0859,921,904.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,754.0,-6.0,0.0,0.0,0800-0859,921,903.0,-18.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1245,1243.0,-2.0,0.0,0.0,1200-1259,1403,1339.0,-24.0,0.0,0.0,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,807.0,7.0,7.0,0.0,0800-0859,930,913.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
5,2021,1,22,5,1/22/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1848.0,-13.0,0.0,0.0,1900-1959,2025,2019.0,-6.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
6,2021,1,22,5,1/22/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,759.0,-1.0,0.0,0.0,0800-0859,930,923.0,-7.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
7,2021,1,5,2,1/5/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1853.0,-8.0,0.0,0.0,1900-1959,2025,2001.0,-24.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df.tail()

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,1639,1645.0,6.0,6.0,0.0,1600-1659,1859,1853.0,-6.0,0.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,838,833.0,-5.0,0.0,0.0,0800-0859,1022,1019.0,-3.0,0.0,0.0,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,610,604.0,-6.0,0.0,0.0,0600-0659,835,822.0,-13.0,0.0,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,1600,1704.0,64.0,64.0,1.0,1600-1659,1744,1841.0,57.0,57.0,1.0,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,EWR,"Newark, NJ",NJ,1635,1630.0,-5.0,0.0,0.0,1600-1659,1802,1812.0,10.0,10.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

#### read_csv options

In [10]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=None, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression: 'CompressionOptions' = 'infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options: 'StorageOptions' = None)
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Delimiter to use. If sep is None, the C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator by Python's builtin sniffer
        tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
        different from ``'\s+'`` will be interpreted as regular expressions and
        will also force the use of the Python parsing engine. Note that regex
        delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, default ``None``
        Alias for sep.
    header : int, list of int, None, default 'infer'
        Row number(s) to use as the column names, and the start of the
        data.  Default behavior is to infer the column names: if no names
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a multi-index on the columns
        e.g. [0,1,3]. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : array-like, optional
        List of column names to use. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : int, str, sequence of int / str, or False, optional, default ``None``
      Column(s) to use as the row labels of the ``DataFrame``, either given as
      string name or column index. If a sequence of int / str is given, a
      MultiIndex is used.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g. when you have a malformed file with delimiters at
      the end of each line.
    usecols : list-like or callable, optional
        Return a subset of the columns. If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a DataFrame from ``data`` with element order preserved use
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
        in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to True. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    squeeze : bool, default False
        If the parsed data only contains one column then return a Series.

        .. deprecated:: 1.4.0
            Append ``.squeeze("columns")`` to the call to ``read_csv`` to squeeze
            the data.
    prefix : str, optional
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...

        .. deprecated:: 1.4.0
           Use a list comprehension on the DataFrame's columns after calling ``read_csv``.
    mangle_dupe_cols : bool, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    dtype : Type name or dict of column -> type, optional
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
        'c': 'Int64'}
        Use `str` or `object` together with suitable `na_values` settings
        to preserve and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The "pyarrow" engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict, optional
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels.
    true_values : list, optional
        Values to consider as True.
    false_values : list, optional
        Values to consider as False.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : list-like, int or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning True if the row should be skipped and False otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c').
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : scalar, str, list-like, or dict, optional
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
        'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    skip_blank_lines : bool, default True
        If True, skip over blank lines rather than interpreting as NaN values.
    parse_dates : bool or list of int or names or list of lists or dict, default False
        The behavior is as follows:

        * boolean. If True -> try parsing the index.
        * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index cannot be represented as an array of datetimes,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an object data type. For
        non-standard datetime parsing, use ``pd.to_datetime`` after
        ``pd.read_csv``. To parse an index or column with a mixture of timezones,
        specify ``date_parser`` to be a partially-applied
        :func:`pandas.to_datetime` with ``utc=True``. See
        :ref:`io.csv.mixed_timezones` for more.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If True and `parse_dates` is enabled, pandas will attempt to infer the
        format of the datetime strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.
    keep_date_col : bool, default False
        If True and `parse_dates` specifies combining multiple columns then
        keep the original columns.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If True, use a cache of unique, converted dates to apply the datetime
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

        .. versionadded:: 0.25.0
    iterator : bool, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.

        .. versionchanged:: 1.2

           ``TextFileReader`` is a context manager.
    chunksize : int, optional
        Return TextFileReader object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

        .. versionchanged:: 1.2

           ``TextFileReader`` is a context manager.
    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and '%s' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', or '.zst' (otherwise no compression). If using
        'zip', the ZIP file must contain only one data file to be read in. Set to
        ``None`` for no decompression. Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``} and other
        key-value pairs are forwarded to ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, or ``zstandard.ZstdDecompressor``, respectively. As an
        example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str, optional
        Thousands separator.
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    lineterminator : str (length 1), optional
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default 0
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
    doublequote : bool, default ``True``
       When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive quotechar elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        One-character string used to escape other characters.
    comment : str, optional
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
        treated as the header.
    encoding : str, optional
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

        .. versionchanged:: 1.2

           When ``encoding`` is ``None``, ``errors="replace"`` is passed to
           ``open()``. Otherwise, ``errors="strict"`` is passed to ``open()``.
           This behavior was previously only the case for ``engine="python"``.

        .. versionchanged:: 1.3.0

           ``encoding_errors`` is a new argument. ``encoding`` has no longer an
           influence on how encoding errors are handled.

    encoding_errors : str, optional, default "strict"
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: `delimiter`, `doublequote`, `escapechar`,
        `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
        override values, a ParserWarning will be issued. See csv.Dialect
        documentation for more details.
    error_bad_lines : bool, optional, default ``None``
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will be dropped from the DataFrame that is
        returned.

        .. deprecated:: 1.3.0
           The ``on_bad_lines`` parameter should be used instead to specify behavior upon
           encountering a bad line instead.
    warn_bad_lines : bool, optional, default ``None``
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output.

        .. deprecated:: 1.3.0
           The ``on_bad_lines`` parameter should be used instead to specify behavior upon
           encountering a bad line instead.
    on_bad_lines : {'error', 'warn', 'skip'} or callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

            - 'error', raise an Exception when a bad line is encountered.
            - 'warn', raise a warning when a bad line is encountered and skip that line.
            - 'skip', skip bad lines without raising or warning when they are encountered.

        .. versionadded:: 1.3.0

            - callable, function with signature
              ``(bad_line: list[str]) -> list[str] | None`` that will process a single
              bad line. ``bad_line`` is a list of strings split by the ``sep``.
              If the function returns ``None``, the bad line will be ignored.
              If the function returns a new list of strings with more elements than
              expected, a ``ParserWarning`` will be emitted while dropping extra elements.
              Only supported when ``engine="python"``

        .. versionadded:: 1.4.0

    delim_whitespace : bool, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
        used as the sep. Equivalent to setting ``sep='\s+'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.
    low_memory : bool, default True
        Internally process the file in chunks, resulting in lower memory use
        while parsing, but possibly mixed type inference.  To ensure no mixed
        types either set False, or specify the type with the `dtype` parameter.
        Note that the entire file is read into a single DataFrame regardless,
        use the `chunksize` or `iterator` parameter to return the data in chunks.
        (Only valid with C parser).
    memory_map : bool, default False
        If a filepath is provided for `filepath_or_buffer`, map the file object
        directly onto memory and access the data directly from there. Using this
        option can improve performance because there is no longer any I/O overhead.
    float_precision : str, optional
        Specifies which converter the C engine should use for floating-point

#### Reading other data formats

- read_table (general delimited data)
- read_fwf
- read_excel
- read_json
- read_xml
- read_html

#### Writing data to text format

In [11]:
df_first5rows = df.head()

In [12]:
df_first5rows.to_csv("sample.csv")

---
## END