## 46-881 Class 5

### Python pandas: Data Exploration and Wrangling (Part 1)

Amr Farahat

CMU / Tepper

2022-11-25

---

## Python pandas: Column-wise operations

In [1]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("PIT_2021.csv")

In [9]:
df.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_CARRIER',
       'OP_CARRIER_FL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR',
       'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'DEP_TIME_BLK',
       'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15',
       'ARR_TIME_BLK', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY'],
      dtype='object')

#### Deleting (dropping) columns

In [10]:
df = df.drop(["YEAR"],axis="columns") # or axis = 1

In [11]:
df.columns

Index(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_CARRIER',
       'OP_CARRIER_FL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR',
       'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'DEP_TIME_BLK',
       'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15',
       'ARR_TIME_BLK', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY'],
      dtype='object')

#### Adding a column with specified values

In [12]:
df["YEAR"] = 2021

In [13]:
df.columns

Index(['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_CARRIER',
       'OP_CARRIER_FL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR',
       'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'CRS_DEP_TIME', 'DEP_TIME',
       'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'DEP_TIME_BLK',
       'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15',
       'ARR_TIME_BLK', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED',
       'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY', 'YEAR'],
      dtype='object')

#### Re-arranging (Re-indexing) columns

In [14]:
col_names = list(df.columns)

In [15]:
col_names.insert(0,col_names.pop())

In [16]:
col_names

['YEAR',
 'MONTH',
 'DAY_OF_MONTH',
 'DAY_OF_WEEK',
 'FL_DATE',
 'OP_CARRIER',
 'OP_CARRIER_FL_NUM',
 'ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'DEP_TIME_BLK',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'ARR_TIME_BLK',
 'CANCELLED',
 'CANCELLATION_CODE',
 'DIVERTED',
 'CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY']

In [17]:
df = df.reindex(columns = col_names)

In [18]:
df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,...,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,...,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,...,0.0,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,...,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,...,0.0,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,...,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,...,1.0,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,...,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

#### Adding computed columns

In [19]:
df["DEP_DELAY_HRS"] = df["DEP_DELAY"] / 60

In [20]:
df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,...,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DEP_DELAY_HRS
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,...,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.016667
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.066667
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.100000
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,...,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.033333
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.116667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,...,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.100000
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,...,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.083333
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,...,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.100000
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,...,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0,1.066667
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,...,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.083333

#### Renaming columns

In [21]:
df = df.rename(columns={"DEP_DELAY_HRS": "departure delay in hours"})

In [22]:
df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,...,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,departure delay in hours
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,...,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.016667
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.066667
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.100000
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,...,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.033333
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,...,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.116667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,...,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.100000
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,...,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.083333
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,...,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.100000
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,...,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0,1.066667
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,...,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,-0.083333

---
## END