## 46-881 Class 5

### Python pandas: Data Exploration and Wrangling (Part 1)

Amr Farahat

CMU / Tepper

2022-11-25

---

## Python pandas: Row-wise operations

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("PIT_2021.csv")

In [3]:
pd.options.display.max_columns = None

In [4]:
df

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2021,1,10,7,1/10/2021 12:00:00 AM,OO,3878,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1901,1900.0,-1.0,0.0,0.0,1900-1959,2025,2023.0,-2.0,0.0,0.0,2000-2059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,2021,1,4,1,1/4/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,756.0,-4.0,0.0,0.0,0800-0859,921,904.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,754.0,-6.0,0.0,0.0,0800-0859,921,903.0,-18.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,2021,1,3,7,1/3/2021 12:00:00 AM,OO,3989,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1245,1243.0,-2.0,0.0,0.0,1200-1259,1403,1339.0,-24.0,0.0,0.0,1400-1459,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,2021,1,11,1,1/11/2021 12:00:00 AM,OO,3934,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,800,807.0,7.0,7.0,0.0,0800-0859,930,913.0,-17.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32615,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2407,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,1639,1645.0,6.0,6.0,0.0,1600-1659,1859,1853.0,-6.0,0.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32616,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2109,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,838,833.0,-5.0,0.0,0.0,0800-0859,1022,1019.0,-3.0,0.0,0.0,1000-1059,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32617,2021,12,20,1,12/20/2021 12:00:00 AM,UA,2108,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,610,604.0,-6.0,0.0,0.0,0600-0659,835,822.0,-13.0,0.0,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32618,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1810,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,1600,1704.0,64.0,64.0,1.0,1600-1659,1744,1841.0,57.0,57.0,1.0,1700-1759,0.0,NaN,0.0,57.0,0.0,0.0,0.0,0.0
32619,2021,12,20,1,12/20/2021 12:00:00 AM,UA,1226,PIT,"Pittsburgh, PA",PA,EWR,"Newark, NJ",NJ,1635,1630.0,-5.0,0.0,0.0,1600-1659,1802,1812.0,10.0,10.0,0.0,1800-1859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

#### Filtering rows by value

Filter to keep only flights by Southwest Airlines

In [5]:
df["OP_CARRIER"] == "WN" ## This is just a boolean

0        False
1        False
2        False
3        False
4        False
         ...
32615    False
32616    False
32617    False
32618    False
32619    False
Name: OP_CARRIER, Length: 32620, dtype: bool

In [6]:
df[df["OP_CARRIER"] == "WN"]

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
97,2021,1,1,5,1/1/2021 12:00:00 AM,WN,4671,PIT,"Pittsburgh, PA",PA,BNA,"Nashville, TN",TN,950,950.0,0.0,0.0,0.0,0900-0959,1030,1047.0,17.0,17.0,1.0,1000-1059,0.0,NaN,0.0,0.0,0.0,17.0,0.0,0.0
98,2021,1,1,5,1/1/2021 12:00:00 AM,WN,3601,PIT,"Pittsburgh, PA",PA,BWI,"Baltimore, MD",MD,1520,1516.0,-4.0,0.0,0.0,1500-1559,1625,1615.0,-10.0,0.0,0.0,1600-1659,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
99,2021,1,1,5,1/1/2021 12:00:00 AM,WN,4681,PIT,"Pittsburgh, PA",PA,BWI,"Baltimore, MD",MD,635,634.0,-1.0,0.0,0.0,0600-0659,750,734.0,-16.0,0.0,0.0,0700-0759,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
100,2021,1,1,5,1/1/2021 12:00:00 AM,WN,4297,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,1710,NaN,NaN,NaN,NaN,1700-1759,1840,NaN,NaN,NaN,NaN,1800-1859,1.0,A,0.0,NaN,NaN,NaN,NaN,NaN
101,2021,1,1,5,1/1/2021 12:00:00 AM,WN,4690,PIT,"Pittsburgh, PA",PA,DEN,"Denver, CO",CO,705,747.0,42.0,42.0,1.0,0700-0759,845,855.0,10.0,10.0,0.0,0800-0859,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31974,2021,12,4,6,12/4/2021 12:00:00 AM,WN,4584,PIT,"Pittsburgh, PA",PA,PHX,"Phoenix, AZ",AZ,1240,1238.0,-2.0,0.0,0.0,1200-1259,1525,1451.0,-34.0,0.0,0.0,1500-1559,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
31975,2021,12,4,6,12/4/2021 12:00:00 AM,WN,5435,PIT,"Pittsburgh, PA",PA,RSW,"Fort Myers, FL",FL,1515,1705.0,110.0,110.0,1.0,1500-1559,1750,1929.0,99.0,99.0,1.0,1700-1759,0.0,NaN,0.0,58.0,0.0,0.0,0.0,41.0
31976,2021,12,4,6,12/4/2021 12:00:00 AM,WN,2104,PIT,"Pittsburgh, PA",PA,SRQ,"Sarasota/Bradenton, FL",FL,905,858.0,-7.0,0.0,0.0,0900-0959,1145,1112.0,-33.0,0.0,0.0,1100-1159,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
31977,2021,12,4,6,12/4/2021 12:00:00 AM,WN,2035,PIT,"Pittsburgh, PA",PA,TPA,"Tampa, FL",FL,710,703.0,-7.0,0.0,0.0,0700-0759,950,918.0,-32.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
31978,2021,12,4,6,12/4/2021 12:00:00 AM,WN,4458,PIT,"Pittsburgh, PA",PA,TPA,"Tampa, FL",FL,1300,1256.0,-4.0,0.0,0.0,1300-1359,1525,1510.0,-15.0,0.0,0.0,1500-1559,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN

Direct flights last December to California?

In [7]:
df[(df["DEST_STATE_ABR"] == "CA") & (df["MONTH"] == 12)]

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
31711,2021,12,1,3,12/1/2021 12:00:00 AM,NK,1955,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,950,1001.0,11.0,11.0,0.0,0900-0959,1215,1148.0,-27.0,0.0,0.0,1200-1259,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32417,2021,12,2,4,12/2/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,730.0,0.0,0.0,0.0,0700-0759,956,944.0,-12.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32418,2021,12,3,5,12/3/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,728.0,-2.0,0.0,0.0,0700-0759,956,938.0,-18.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32419,2021,12,5,7,12/5/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,730.0,0.0,0.0,0.0,0700-0759,956,933.0,-23.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32420,2021,12,6,1,12/6/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,727.0,-3.0,0.0,0.0,0700-0759,956,947.0,-9.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32421,2021,12,9,4,12/9/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,724.0,-6.0,0.0,0.0,0700-0759,956,959.0,3.0,3.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32422,2021,12,10,5,12/10/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,727.0,-3.0,0.0,0.0,0700-0759,956,943.0,-13.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32423,2021,12,12,7,12/12/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,749.0,19.0,19.0,1.0,0700-0759,956,950.0,-6.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32424,2021,12,13,1,12/13/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,721.0,-9.0,0.0,0.0,0700-0759,956,954.0,-2.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32425,2021,12,16,4,12/16/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,724.0,-6.0,0.0,0.0,0700-0759,947,958.0,11.0,11.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32426,2021,12,17,5,12/17/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,752.0,22.0,22.0,1.0,0700-0759,947,958.0,11.0,11.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32427,2021,12,18,6,12/18/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,814.0,44.0,44.0,1.0,0700-0759,947,1020.0,33.0,33.0,1.0,0900-0959,0.0,NaN,0.0,24.0,0.0,9.0,0.0,0.0
32428,2021,12,19,7,12/19/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,NaN,NaN,NaN,NaN,0700-0759,947,NaN,NaN,NaN,NaN,0900-0959,1.0,A,0.0,NaN,NaN,NaN,NaN,NaN
32429,2021,12,20,1,12/20/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,733.0,3.0,3.0,0.0,0700-0759,947,939.0,-8.0,0.0,0.0,0900-0959,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
32430,2021,12,21,2,12/21/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,957.0,147.0,147.0,1.0,0700-0759,947,1230.0,163.0,163.0,1.0,0900-0959,0.0,NaN,0.0,8.0,0.0,155.0,0.0,0.0
32431,2021,12,22,3,12/22/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,853.0,83.0,83.0,1.0,0700-0759,947,1104.0,77.0,77.0,1.0,0900-0959,0.0,NaN,0.0,17.0,0.0,1.0,0.0,59.0
32432,2021,12,23,4,12/23/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,729.0,-1.0,0.0,0.0,0700-0759,947,1010.0,23.0,23.0,1.0,0900-0959,0.0,NaN,0.0,0.0,0.0,23.0,0.0,0.0
32433,2021,12,24,5,12/24/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,736.0,6.0,6.0,0.0,0700-0759,947,1048.0,61.0,61.0,1.0,0900-0959,0.0,NaN,0.0,6.0,0.0,55.0,0.0,0.0
32434,2021,12,26,7,12/26/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,740,819.0,39.0,39.0,1.0,0700-0759,957,1116.0,79.0,79.0,1.0,0900-0959,0.0,NaN,0.0,39.0,0.0,40.0,0.0,0.0
32435,2021,12,27,1,12/27/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,740,741.0,1.0,1.0,0.0,0700-0759,957,1049.0,52.0,52.0,1.0,0900-0959,0.0,NaN,0.0,1.0,0.0,51.0,0.0,0.0
32436,2021,12,28,2,12/28/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,740,739.0,-1.0,0.0,0.0,0700-0759,957,1033.0,36.0,36.0,1.0,0900-0959,0.0,NaN,0.0,0.0,0.0,36.0,0.0,0.0
32437,2021,12,29,3,12/29/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,740,821.0,41.0,41.0,1.0,0700-0759,957,1119.0,82.0,82.0,1.0,0900-0959,0.0,NaN,0.0,22.0,0.0,41.0,0.0,19.0
32438,2021,12,30,4,12/30/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,740,1010.0,150.0,150.0,1.0,0700-0759,957,1302.0,185.0,185.0,1.0,0900-0959,0.0,NaN,0.0,150.0,0.0,35.0,0.0,0.0
32439,2021,12,31,5,12/31/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,740,815.0,35.0,35.0,1.0,0700-0759,957,1104.0,67.0,67.0,1.0,0900-0959,0.0,NaN,0.0,35.0,0.0,32.0,0.0,0.0

#### Sorting

In [8]:
df.sort_values(by=["DEP_DELAY"], ascending=False)

,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_TIME_BLK,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
28913,2021,11,11,4,11/11/2021 12:00:00 AM,OO,3956,PIT,"Pittsburgh, PA",PA,DTW,"Detroit, MI",MI,1031,1146.0,1515.0,1515.0,1.0,1000-1059,1145,NaN,NaN,NaN,NaN,1100-1159,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
26530,2021,11,30,2,11/30/2021 12:00:00 AM,NK,530,PIT,"Pittsburgh, PA",PA,RSW,"Fort Myers, FL",FL,1155,1148.0,1433.0,1433.0,1.0,1100-1159,1419,1420.0,1441.0,1441.0,1.0,1400-1459,0.0,NaN,0.0,1433.0,0.0,8.0,0.0,0.0
29965,2021,12,31,5,12/31/2021 12:00:00 AM,YV,6336,PIT,"Pittsburgh, PA",PA,IAH,"Houston, TX",TX,1300,956.0,1256.0,1256.0,1.0,1300-1359,1532,1204.0,1232.0,1232.0,1.0,1500-1559,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1232.0
6278,2021,4,25,7,4/25/2021 12:00:00 AM,NK,1392,PIT,"Pittsburgh, PA",PA,TPA,"Tampa, FL",FL,1355,1041.0,1246.0,1246.0,1.0,1300-1359,1609,1253.0,1244.0,1244.0,1.0,1600-1659,0.0,NaN,0.0,0.0,0.0,0.0,0.0,1244.0
16283,2021,8,8,7,8/8/2021 12:00:00 AM,OO,4147,PIT,"Pittsburgh, PA",PA,MSP,"Minneapolis, MN",MN,1600,1128.0,1168.0,1168.0,1.0,1600-1659,1715,1236.0,1161.0,1161.0,1.0,1700-1759,0.0,NaN,0.0,1161.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32412,2021,12,27,1,12/27/2021 12:00:00 AM,NK,530,PIT,"Pittsburgh, PA",PA,RSW,"Fort Myers, FL",FL,1155,NaN,NaN,NaN,NaN,1100-1159,1431,NaN,NaN,NaN,NaN,1400-1459,1.0,B,0.0,NaN,NaN,NaN,NaN,NaN
32428,2021,12,19,7,12/19/2021 12:00:00 AM,NK,653,PIT,"Pittsburgh, PA",PA,LAX,"Los Angeles, CA",CA,730,NaN,NaN,NaN,NaN,0700-0759,947,NaN,NaN,NaN,NaN,0900-0959,1.0,A,0.0,NaN,NaN,NaN,NaN,NaN
32451,2021,12,18,6,12/18/2021 12:00:00 AM,NK,721,PIT,"Pittsburgh, PA",PA,MCO,"Orlando, FL",FL,730,NaN,NaN,NaN,NaN,0700-0759,958,NaN,NaN,NaN,NaN,0900-0959,1.0,A,0.0,NaN,NaN,NaN,NaN,NaN
32540,2021,12,27,1,12/27/2021 12:00:00 AM,OO,4003,PIT,"Pittsburgh, PA",PA,DTW,"Detroit, MI",MI,1200,NaN,NaN,NaN,NaN,1200-1259,1311,NaN,NaN,NaN,NaN,1300-1359,1.0,A,0.0,NaN,NaN,NaN,NaN,NaN
32543,2021,12,27,1,12/27/2021 12:00:00 AM,OO,4164,PIT,"Pittsburgh, PA",PA,DTW,"Detroit, MI",MI,1035,NaN,NaN,NaN,NaN,1000-1059,1145,NaN,NaN,NaN,NaN,1100-1159,1.0,A,0.0,NaN,NaN,NaN,NaN,NaN

---
## END