#### Carnegie Mellon University - Tepper School of Business
#### 46-886 - Machine Learning Fundamentals
#### 22/23 - Mini 4 - Section M4 - Farahat
---

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import statsmodels.api as sm
from graphviz import Source
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_graphviz
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoCV
from sklearn.linear_model import ElasticNetCV

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [49]:
pd.options.display.max_columns = None

In [50]:
def OSR2(y_actual,y_pred,baseline):
    residuals = y_actual - y_pred
    SSR = np.sum((residuals)^2)
    SST = np.sum((y_actual - baseline)^2)
    R2 = 1 - SSR / SST
    return(R2)

In [51]:
df = pd.read_csv("Diabetes_V2.csv")

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AGE     442 non-null    int64
 1   SEX     442 non-null    int64
 2   BMI     442 non-null    float64
 3   BP      442 non-null    float64
 4   S1      442 non-null    int64
 5   S2      442 non-null    float64
 6   S3      442 non-null    int64
 7   S4      442 non-null    float64
 8   S5      442 non-null    float64
 9   S6      442 non-null    int64
 10  Y       442 non-null    int64
dtypes: float64(5), int64(6)
memory usage: 38.1 KB

### Adding quadratic and Interaction terms

In [53]:
df

     AGE  SEX   BMI      BP   S1     S2  S3    S4      S5   S6    Y
0     59    2  32.1  101.00  157   93.2  38  4.00  4.8598   87  151
1     48    1  21.6   87.00  183  103.2  70  3.00  3.8918   69   75
2     72    2  30.5   93.00  156   93.6  41  4.00  4.6728   85  141
3     24    1  25.3   84.00  198  131.4  40  5.00  4.8903   89  206
4     50    1  23.0  101.00  192  125.4  52  4.00  4.2905   80  135
..   ...  ...   ...     ...  ...    ...  ..   ...     ...  ...  ...
437   60    2  28.2  112.00  185  113.8  42  4.00  4.9836   93  178
438   47    2  24.9   75.00  225  166.0  42  5.00  4.4427  102  104
439   60    2  24.9   99.67  162  106.6  43  3.77  4.1271   95  132
440   36    1  30.0   95.00  201  125.2  42  4.79  5.1299   85  220
441   36    1  19.6   71.00  250  133.2  97  3.00  4.5951   92   57

[442 rows x 11 columns]

In [54]:
y = df["Y"]

In [55]:
X = df.drop("Y", axis=1)

In [56]:
X = pd.get_dummies(X, drop_first=True)

In [57]:
X

     AGE  SEX   BMI      BP   S1     S2  S3    S4      S5   S6
0     59    2  32.1  101.00  157   93.2  38  4.00  4.8598   87
1     48    1  21.6   87.00  183  103.2  70  3.00  3.8918   69
2     72    2  30.5   93.00  156   93.6  41  4.00  4.6728   85
3     24    1  25.3   84.00  198  131.4  40  5.00  4.8903   89
4     50    1  23.0  101.00  192  125.4  52  4.00  4.2905   80
..   ...  ...   ...     ...  ...    ...  ..   ...     ...  ...
437   60    2  28.2  112.00  185  113.8  42  4.00  4.9836   93
438   47    2  24.9   75.00  225  166.0  42  5.00  4.4427  102
439   60    2  24.9   99.67  162  106.6  43  3.77  4.1271   95
440   36    1  30.0   95.00  201  125.2  42  4.79  5.1299   85
441   36    1  19.6   71.00  250  133.2  97  3.00  4.5951   92

[442 rows x 10 columns]

In [58]:
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[1.00000000e+00, 5.90000000e+01, 2.00000000e+00, ...,
        2.36176560e+01, 4.22802600e+02, 7.56900000e+03],
       [1.00000000e+00, 4.80000000e+01, 1.00000000e+00, ...,
        1.51461072e+01, 2.68534200e+02, 4.76100000e+03],
       [1.00000000e+00, 7.20000000e+01, 2.00000000e+00, ...,
        2.18350598e+01, 3.97188000e+02, 7.22500000e+03],
       ...,
       [1.00000000e+00, 6.00000000e+01, 2.00000000e+00, ...,
        1.70329544e+01, 3.92074500e+02, 9.02500000e+03],
       [1.00000000e+00, 3.60000000e+01, 1.00000000e+00, ...,
        2.63158740e+01, 4.36041500e+02, 7.22500000e+03],
       [1.00000000e+00, 3.60000000e+01, 1.00000000e+00, ...,
        2.11149440e+01, 4.22749200e+02, 8.46400000e+03]])

In [59]:
X1 = X.copy()
X1

     AGE  SEX   BMI      BP   S1     S2  S3    S4      S5   S6
0     59    2  32.1  101.00  157   93.2  38  4.00  4.8598   87
1     48    1  21.6   87.00  183  103.2  70  3.00  3.8918   69
2     72    2  30.5   93.00  156   93.6  41  4.00  4.6728   85
3     24    1  25.3   84.00  198  131.4  40  5.00  4.8903   89
4     50    1  23.0  101.00  192  125.4  52  4.00  4.2905   80
..   ...  ...   ...     ...  ...    ...  ..   ...     ...  ...
437   60    2  28.2  112.00  185  113.8  42  4.00  4.9836   93
438   47    2  24.9   75.00  225  166.0  42  5.00  4.4427  102
439   60    2  24.9   99.67  162  106.6  43  3.77  4.1271   95
440   36    1  30.0   95.00  201  125.2  42  4.79  5.1299   85
441   36    1  19.6   71.00  250  133.2  97  3.00  4.5951   92

[442 rows x 10 columns]

In [60]:
arr = poly.fit_transform(X1)

In [61]:
arr = pd.DataFrame(poly.fit_transform(X1))
#pd.DataFrame(arr).to_csv('sample0416.csv')

In [62]:
arr

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65
0,1.0,59.0,2.0,32.1,101.00,157.0,93.2,38.0,4.00,4.8598,87.0,3481.0,118.0,1893.9,5959.0,9263.0,5498.8,2242.0,236.00,286.7282,5133.0,4.0,64.2,202.00,314.0,186.4,76.0,8.00,9.7196,174.0,1030.41,3242.100,5039.7,2991.72,1219.8,128.400,155.99958,2792.7,10201.0000,15857.00,9413.200,3838.00,404.0000,490.839800,8787.00,24649.0,14632.4,5966.0,628.00,762.9886,13659.0,8686.24,3541.6,372.800,452.93336,8108.4,1444.0,152.00,184.6724,3306.0,16.0000,19.439200,348.00,23.617656,422.8026,7569.0
1,1.0,48.0,1.0,21.6,87.00,183.0,103.2,70.0,3.00,3.8918,69.0,2304.0,48.0,1036.8,4176.0,8784.0,4953.6,3360.0,144.00,186.8064,3312.0,1.0,21.6,87.00,183.0,103.2,70.0,3.00,3.8918,69.0,466.56,1879.200,3952.8,2229.12,1512.0,64.800,84.06288,1490.4,7569.0000,15921.00,8978.400,6090.00,261.0000,338.586600,6003.00,33489.0,18885.6,12810.0,549.00,712.1994,12627.0,10650.24,7224.0,309.600,401.63376,7120.8,4900.0,210.00,272.4260,4830.0,9.0000,11.675400,207.00,15.146107,268.5342,4761.0
2,1.0,72.0,2.0,30.5,93.00,156.0,93.6,41.0,4.00,4.6728,85.0,5184.0,144.0,2196.0,6696.0,11232.0,6739.2,2952.0,288.00,336.4416,6120.0,4.0,61.0,186.00,312.0,187.2,82.0,8.00,9.3456,170.0,930.25,2836.500,4758.0,2854.80,1250.5,122.000,142.52040,2592.5,8649.0000,14508.00,8704.800,3813.00,372.0000,434.570400,7905.00,24336.0,14601.6,6396.0,624.00,728.9568,13260.0,8760.96,3837.6,374.400,437.37408,7956.0,1681.0,164.00,191.5848,3485.0,16.0000,18.691200,340.00,21.835060,397.1880,7225.0
3,1.0,24.0,1.0,25.3,84.00,198.0,131.4,40.0,5.00,4.8903,89.0,576.0,24.0,607.2,2016.0,4752.0,3153.6,960.0,120.00,117.3672,2136.0,1.0,25.3,84.00,198.0,131.4,40.0,5.00,4.8903,89.0,640.09,2125.200,5009.4,3324.42,1012.0,126.500,123.72459,2251.7,7056.0000,16632.00,11037.600,3360.00,420.0000,410.785200,7476.00,39204.0,26017.2,7920.0,990.00,968.2794,17622.0,17265.96,5256.0,657.000,642.58542,11694.6,1600.0,200.00,195.6120,3560.0,25.0000,24.451500,445.00,23.915034,435.2367,7921.0
4,1.0,50.0,1.0,23.0,101.00,192.0,125.4,52.0,4.00,4.2905,80.0,2500.0,50.0,1150.0,5050.0,9600.0,6270.0,2600.0,200.00,214.5250,4000.0,1.0,23.0,101.00,192.0,125.4,52.0,4.00,4.2905,80.0,529.00,2323.000,4416.0,2884.20,1196.0,92.000,98.68150,1840.0,10201.0000,19392.00,12665.400,5252.00,404.0000,433.340500,8080.00,36864.0,24076.8,9984.0,768.00,823.7760,15360.0,15725.16,6520.8,501.600,538.02870,10032.0,2704.0,208.00,223.1060,4160.0,16.0000,17.162000,320.00,18.408390,343.2400,6400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,1.0,60.0,2.0,28.2,112.00,185.0,113.8,42.0,4.00,4.9836,93.0,3600.0,120.0,1692.0,6720.0,11100.0,6828.0,2520.0,240.00,299.0160,5580.0,4.0,56.4,224.00,370.0,227.6,84.0,8.00,9.9672,186.0,795.24,3158.400,5217.0,3209.16,1184.4,112.800,140.53752,2622.6,12544.0000,20720.00,12745.600,4704.00,448.0000,558.163200,10416.00,34225.0,21053.0,7770.0,740.00,921.9660,17205.0,12950.44,4779.6,455.200,567.13368,10583.4,1764.0,168.00,209.3112,3906.0,16.0000,19.934400,372.00,24.836269,463.4748,8649.0
438,1.0,47.0,2.0,24.9,75.00,225.0,166.0,42.0,5.00,4.4427,102.0,2209.0,94.0,1170.3,3525.0,10575.0,7802.0,1974.0,235.00,208.8069,4794.0,4.0,49.8,150.00,450.0,332.0,84.0,10.00,8.8854,204.0,620.01,1867.500,5602.5,4133.40,1045.8,124.500,110.62323,2539.8,5625.0000,16875.00,12450.000,3150.00,375.0000,333.202500,7650.00,50625.0,37350.0,9450.0,1125.00,999.6075,22950.0,27556.00,6972.0,830.000,737.48820,16932.0,1764.0,210.00,186.5934,4284.0,25.0000,22.213500,510.00,19.737583,453.1554,10404.0
439,1.0,60.0,2.0,24.9,99.67,162.0,106.6,43.0,3.77,4.1271,95.0,3600.0,120.0,1494.0,5980.2,9720.0,6396.0,2580.0,226.20,247.6260,5700.0,4.0,49.8,199.34,324.0,213.2,86.0,7.54,8.2542,190.0,620.01,2481.783,4033.8,2654.34,1070.7,93.873,102.76479,2365.5,9934.1089,16146.54,10624.822,4285.81,375.7559,411.348057,9468.65,26244.0,17269.2,6966.0,610.74,668.5902,15390.0,11363.56,4583.8,401.882,439.94886,10127.0,1849.0,162.11,177.4653,4085.0,14.2129,15.559167,358.15,17.032954,392.0745,9025.0
440,1.0,36.0,1.0,30.0,95.00,201.0,125.2,42.0,4.79,5.1299,85.0,1296.0,36.0,1080.0,3420.0,7236.0,4507.2,1512.0,172.44,184.6764,3060.0,1.0,30.0,95.00,201.0,125.2,42.0,4.79,5.1299,85.0,900.00,2850.000,6030.0,3756.00,1260.0,143.700,153.89700,2550.0,9025.0000,19095.00,11894.000,3990.00,455.0500,487.340500,8075.00,40401.0,25165.2,8442.0,962.79,1031.1099,17085.0,15675.04,5258.4,599.708,642.26348,10642.0,1764.0,201.18,215.4558,3570.0,22.9441,24.572221,407.15,26.315874,436.0415,7225.0
441,1.0,36.0,1.0,19.6,71.00,250.0,133.2,97.0,3.00,4.5951,92.0,1296.0,36.0,705.6,2556.0,9000.0,4795.2,3492.0,108.00,165.4236,3312.0,1.0,19.6,71.00,250.0,133.2,97.0,3.00,4.5951,92.0,384.16,1391.600,4900.0,2610.72,1901.2,58.800,90.06396,1803.2,5041.0000,17750.00,9457.200,6887.00,213.0000,326.252100,6532.00,62500.0,33300.0,24250.0,750.00,1148.7750,23000.0,17742.24,12920.4,399.600,612.06732,12254.4,9409.0,291.00,445.7247,8924.0,9.0000,13.785300,276.00,21.114944,422.7492,8464.0

In [64]:
X1 = arr

In [65]:
X1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65
0,1.0,59.0,2.0,32.1,101.00,157.0,93.2,38.0,4.00,4.8598,87.0,3481.0,118.0,1893.9,5959.0,9263.0,5498.8,2242.0,236.00,286.7282,5133.0,4.0,64.2,202.00,314.0,186.4,76.0,8.00,9.7196,174.0,1030.41,3242.100,5039.7,2991.72,1219.8,128.400,155.99958,2792.7,10201.0000,15857.00,9413.200,3838.00,404.0000,490.839800,8787.00,24649.0,14632.4,5966.0,628.00,762.9886,13659.0,8686.24,3541.6,372.800,452.93336,8108.4,1444.0,152.00,184.6724,3306.0,16.0000,19.439200,348.00,23.617656,422.8026,7569.0
1,1.0,48.0,1.0,21.6,87.00,183.0,103.2,70.0,3.00,3.8918,69.0,2304.0,48.0,1036.8,4176.0,8784.0,4953.6,3360.0,144.00,186.8064,3312.0,1.0,21.6,87.00,183.0,103.2,70.0,3.00,3.8918,69.0,466.56,1879.200,3952.8,2229.12,1512.0,64.800,84.06288,1490.4,7569.0000,15921.00,8978.400,6090.00,261.0000,338.586600,6003.00,33489.0,18885.6,12810.0,549.00,712.1994,12627.0,10650.24,7224.0,309.600,401.63376,7120.8,4900.0,210.00,272.4260,4830.0,9.0000,11.675400,207.00,15.146107,268.5342,4761.0
2,1.0,72.0,2.0,30.5,93.00,156.0,93.6,41.0,4.00,4.6728,85.0,5184.0,144.0,2196.0,6696.0,11232.0,6739.2,2952.0,288.00,336.4416,6120.0,4.0,61.0,186.00,312.0,187.2,82.0,8.00,9.3456,170.0,930.25,2836.500,4758.0,2854.80,1250.5,122.000,142.52040,2592.5,8649.0000,14508.00,8704.800,3813.00,372.0000,434.570400,7905.00,24336.0,14601.6,6396.0,624.00,728.9568,13260.0,8760.96,3837.6,374.400,437.37408,7956.0,1681.0,164.00,191.5848,3485.0,16.0000,18.691200,340.00,21.835060,397.1880,7225.0
3,1.0,24.0,1.0,25.3,84.00,198.0,131.4,40.0,5.00,4.8903,89.0,576.0,24.0,607.2,2016.0,4752.0,3153.6,960.0,120.00,117.3672,2136.0,1.0,25.3,84.00,198.0,131.4,40.0,5.00,4.8903,89.0,640.09,2125.200,5009.4,3324.42,1012.0,126.500,123.72459,2251.7,7056.0000,16632.00,11037.600,3360.00,420.0000,410.785200,7476.00,39204.0,26017.2,7920.0,990.00,968.2794,17622.0,17265.96,5256.0,657.000,642.58542,11694.6,1600.0,200.00,195.6120,3560.0,25.0000,24.451500,445.00,23.915034,435.2367,7921.0
4,1.0,50.0,1.0,23.0,101.00,192.0,125.4,52.0,4.00,4.2905,80.0,2500.0,50.0,1150.0,5050.0,9600.0,6270.0,2600.0,200.00,214.5250,4000.0,1.0,23.0,101.00,192.0,125.4,52.0,4.00,4.2905,80.0,529.00,2323.000,4416.0,2884.20,1196.0,92.000,98.68150,1840.0,10201.0000,19392.00,12665.400,5252.00,404.0000,433.340500,8080.00,36864.0,24076.8,9984.0,768.00,823.7760,15360.0,15725.16,6520.8,501.600,538.02870,10032.0,2704.0,208.00,223.1060,4160.0,16.0000,17.162000,320.00,18.408390,343.2400,6400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,1.0,60.0,2.0,28.2,112.00,185.0,113.8,42.0,4.00,4.9836,93.0,3600.0,120.0,1692.0,6720.0,11100.0,6828.0,2520.0,240.00,299.0160,5580.0,4.0,56.4,224.00,370.0,227.6,84.0,8.00,9.9672,186.0,795.24,3158.400,5217.0,3209.16,1184.4,112.800,140.53752,2622.6,12544.0000,20720.00,12745.600,4704.00,448.0000,558.163200,10416.00,34225.0,21053.0,7770.0,740.00,921.9660,17205.0,12950.44,4779.6,455.200,567.13368,10583.4,1764.0,168.00,209.3112,3906.0,16.0000,19.934400,372.00,24.836269,463.4748,8649.0
438,1.0,47.0,2.0,24.9,75.00,225.0,166.0,42.0,5.00,4.4427,102.0,2209.0,94.0,1170.3,3525.0,10575.0,7802.0,1974.0,235.00,208.8069,4794.0,4.0,49.8,150.00,450.0,332.0,84.0,10.00,8.8854,204.0,620.01,1867.500,5602.5,4133.40,1045.8,124.500,110.62323,2539.8,5625.0000,16875.00,12450.000,3150.00,375.0000,333.202500,7650.00,50625.0,37350.0,9450.0,1125.00,999.6075,22950.0,27556.00,6972.0,830.000,737.48820,16932.0,1764.0,210.00,186.5934,4284.0,25.0000,22.213500,510.00,19.737583,453.1554,10404.0
439,1.0,60.0,2.0,24.9,99.67,162.0,106.6,43.0,3.77,4.1271,95.0,3600.0,120.0,1494.0,5980.2,9720.0,6396.0,2580.0,226.20,247.6260,5700.0,4.0,49.8,199.34,324.0,213.2,86.0,7.54,8.2542,190.0,620.01,2481.783,4033.8,2654.34,1070.7,93.873,102.76479,2365.5,9934.1089,16146.54,10624.822,4285.81,375.7559,411.348057,9468.65,26244.0,17269.2,6966.0,610.74,668.5902,15390.0,11363.56,4583.8,401.882,439.94886,10127.0,1849.0,162.11,177.4653,4085.0,14.2129,15.559167,358.15,17.032954,392.0745,9025.0
440,1.0,36.0,1.0,30.0,95.00,201.0,125.2,42.0,4.79,5.1299,85.0,1296.0,36.0,1080.0,3420.0,7236.0,4507.2,1512.0,172.44,184.6764,3060.0,1.0,30.0,95.00,201.0,125.2,42.0,4.79,5.1299,85.0,900.00,2850.000,6030.0,3756.00,1260.0,143.700,153.89700,2550.0,9025.0000,19095.00,11894.000,3990.00,455.0500,487.340500,8075.00,40401.0,25165.2,8442.0,962.79,1031.1099,17085.0,15675.04,5258.4,599.708,642.26348,10642.0,1764.0,201.18,215.4558,3570.0,22.9441,24.572221,407.15,26.315874,436.0415,7225.0
441,1.0,36.0,1.0,19.6,71.00,250.0,133.2,97.0,3.00,4.5951,92.0,1296.0,36.0,705.6,2556.0,9000.0,4795.2,3492.0,108.00,165.4236,3312.0,1.0,19.6,71.00,250.0,133.2,97.0,3.00,4.5951,92.0,384.16,1391.600,4900.0,2610.72,1901.2,58.800,90.06396,1803.2,5041.0000,17750.00,9457.200,6887.00,213.0000,326.252100,6532.00,62500.0,33300.0,24250.0,750.00,1148.7750,23000.0,17742.24,12920.4,399.600,612.06732,12254.4,9409.0,291.00,445.7247,8924.0,9.0000,13.785300,276.00,21.114944,422.7492,8464.0

### Standardizing the Data

In [66]:
scaler = StandardScaler()
scaler.fit(X1)

StandardScaler()

In [67]:
scaler.mean_

array([1.00000000e+00, 4.85180995e+01, 1.46832579e+00, 2.63757919e+01,
       9.46470136e+01, 1.89140271e+02, 1.15439140e+02, 4.97873303e+01,
       4.07024887e+00, 4.64141086e+00, 9.12601810e+01, 2.52546380e+03,
       7.23755656e+01, 1.29039864e+03, 4.65277357e+03, 9.29444344e+03,
       5.68809910e+03, 2.40286425e+03, 2.00921222e+02, 2.27042510e+02,
       4.47314027e+03, 2.40497738e+00, 3.89223982e+01, 1.40634163e+02,
       2.78328054e+02, 1.71664480e+02, 7.06606335e+01, 6.19006787e+00,
       6.85413778e+00, 1.35192308e+02, 7.15158032e+02, 2.52049815e+03,
       5.02682964e+03, 3.07981240e+03, 1.29227014e+03, 1.09709962e+02,
       1.23448280e+02, 2.42675679e+03, 9.14892876e+03, 1.80173604e+04,
       1.10038446e+04, 4.68030066e+03, 3.89825183e+02, 4.42132269e+02,
       8.69944505e+03, 3.69690498e+04, 2.27758265e+04, 9.43980995e+03,
       7.94008145e+02, 8.87176361e+02, 1.73902738e+04, 1.42490579e+04,
       5.67029276e+03, 4.95702984e+02, 5.40846930e+02, 1.06363722e+04,
       2.64571041e+03, 1.90348416e+02, 2.28397025e+02, 4.50299321e+03,
       1.82284192e+01, 1.93072653e+01, 3.77627172e+02, 2.18149693e+01,
       4.26360286e+02, 8.46028733e+03])

In [68]:
scaler.scale_

array([1.00000000e+00, 1.30941902e+01, 4.98995736e-01, 4.41312086e+00,
       1.38156283e+01, 3.45688801e+01, 3.03786576e+01, 1.29202224e+01,
       1.28898929e+00, 5.21799287e-01, 1.14833225e+01, 1.24614006e+03,
       3.40398906e+01, 4.29978296e+02, 1.58561463e+03, 3.30468163e+03,
       2.31779980e+03, 9.01504685e+02, 9.02050241e+01, 7.15809975e+01,
       1.44887996e+03, 1.49698721e+00, 1.52765523e+01, 5.60402453e+01,
       1.10825894e+02, 8.00109361e+01, 2.46067301e+01, 3.31176577e+00,
       2.56499262e+00, 5.21407479e+01, 2.45743836e+02, 6.63791826e+02,
       1.37730932e+03, 1.05635853e+03, 3.15300040e+02, 4.54939970e+01,
       2.95838117e+01, 5.97220413e+02, 2.67987374e+03, 4.67033449e+03,
       3.53866557e+03, 1.29192816e+03, 1.48607476e+02, 9.60783701e+01,
       1.97920123e+03, 1.36361190e+04, 1.00163084e+04, 3.12145655e+03,
       3.60500509e+02, 2.31685239e+02, 4.39271005e+03, 7.55141865e+03,
       1.87253840e+03, 2.66934861e+02, 1.71606112e+02, 3.43748936e+03,
       1.44211384e+03, 3.67478328e+01, 5.44780169e+01, 1.15255231e+03,
       1.19312222e+01, 7.72440216e+00, 1.47968535e+02, 4.93623899e+00,
       8.73241164e+01, 2.13216325e+03])

In [69]:
X1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65
0,1.0,59.0,2.0,32.1,101.00,157.0,93.2,38.0,4.00,4.8598,87.0,3481.0,118.0,1893.9,5959.0,9263.0,5498.8,2242.0,236.00,286.7282,5133.0,4.0,64.2,202.00,314.0,186.4,76.0,8.00,9.7196,174.0,1030.41,3242.100,5039.7,2991.72,1219.8,128.400,155.99958,2792.7,10201.0000,15857.00,9413.200,3838.00,404.0000,490.839800,8787.00,24649.0,14632.4,5966.0,628.00,762.9886,13659.0,8686.24,3541.6,372.800,452.93336,8108.4,1444.0,152.00,184.6724,3306.0,16.0000,19.439200,348.00,23.617656,422.8026,7569.0
1,1.0,48.0,1.0,21.6,87.00,183.0,103.2,70.0,3.00,3.8918,69.0,2304.0,48.0,1036.8,4176.0,8784.0,4953.6,3360.0,144.00,186.8064,3312.0,1.0,21.6,87.00,183.0,103.2,70.0,3.00,3.8918,69.0,466.56,1879.200,3952.8,2229.12,1512.0,64.800,84.06288,1490.4,7569.0000,15921.00,8978.400,6090.00,261.0000,338.586600,6003.00,33489.0,18885.6,12810.0,549.00,712.1994,12627.0,10650.24,7224.0,309.600,401.63376,7120.8,4900.0,210.00,272.4260,4830.0,9.0000,11.675400,207.00,15.146107,268.5342,4761.0
2,1.0,72.0,2.0,30.5,93.00,156.0,93.6,41.0,4.00,4.6728,85.0,5184.0,144.0,2196.0,6696.0,11232.0,6739.2,2952.0,288.00,336.4416,6120.0,4.0,61.0,186.00,312.0,187.2,82.0,8.00,9.3456,170.0,930.25,2836.500,4758.0,2854.80,1250.5,122.000,142.52040,2592.5,8649.0000,14508.00,8704.800,3813.00,372.0000,434.570400,7905.00,24336.0,14601.6,6396.0,624.00,728.9568,13260.0,8760.96,3837.6,374.400,437.37408,7956.0,1681.0,164.00,191.5848,3485.0,16.0000,18.691200,340.00,21.835060,397.1880,7225.0
3,1.0,24.0,1.0,25.3,84.00,198.0,131.4,40.0,5.00,4.8903,89.0,576.0,24.0,607.2,2016.0,4752.0,3153.6,960.0,120.00,117.3672,2136.0,1.0,25.3,84.00,198.0,131.4,40.0,5.00,4.8903,89.0,640.09,2125.200,5009.4,3324.42,1012.0,126.500,123.72459,2251.7,7056.0000,16632.00,11037.600,3360.00,420.0000,410.785200,7476.00,39204.0,26017.2,7920.0,990.00,968.2794,17622.0,17265.96,5256.0,657.000,642.58542,11694.6,1600.0,200.00,195.6120,3560.0,25.0000,24.451500,445.00,23.915034,435.2367,7921.0
4,1.0,50.0,1.0,23.0,101.00,192.0,125.4,52.0,4.00,4.2905,80.0,2500.0,50.0,1150.0,5050.0,9600.0,6270.0,2600.0,200.00,214.5250,4000.0,1.0,23.0,101.00,192.0,125.4,52.0,4.00,4.2905,80.0,529.00,2323.000,4416.0,2884.20,1196.0,92.000,98.68150,1840.0,10201.0000,19392.00,12665.400,5252.00,404.0000,433.340500,8080.00,36864.0,24076.8,9984.0,768.00,823.7760,15360.0,15725.16,6520.8,501.600,538.02870,10032.0,2704.0,208.00,223.1060,4160.0,16.0000,17.162000,320.00,18.408390,343.2400,6400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,1.0,60.0,2.0,28.2,112.00,185.0,113.8,42.0,4.00,4.9836,93.0,3600.0,120.0,1692.0,6720.0,11100.0,6828.0,2520.0,240.00,299.0160,5580.0,4.0,56.4,224.00,370.0,227.6,84.0,8.00,9.9672,186.0,795.24,3158.400,5217.0,3209.16,1184.4,112.800,140.53752,2622.6,12544.0000,20720.00,12745.600,4704.00,448.0000,558.163200,10416.00,34225.0,21053.0,7770.0,740.00,921.9660,17205.0,12950.44,4779.6,455.200,567.13368,10583.4,1764.0,168.00,209.3112,3906.0,16.0000,19.934400,372.00,24.836269,463.4748,8649.0
438,1.0,47.0,2.0,24.9,75.00,225.0,166.0,42.0,5.00,4.4427,102.0,2209.0,94.0,1170.3,3525.0,10575.0,7802.0,1974.0,235.00,208.8069,4794.0,4.0,49.8,150.00,450.0,332.0,84.0,10.00,8.8854,204.0,620.01,1867.500,5602.5,4133.40,1045.8,124.500,110.62323,2539.8,5625.0000,16875.00,12450.000,3150.00,375.0000,333.202500,7650.00,50625.0,37350.0,9450.0,1125.00,999.6075,22950.0,27556.00,6972.0,830.000,737.48820,16932.0,1764.0,210.00,186.5934,4284.0,25.0000,22.213500,510.00,19.737583,453.1554,10404.0
439,1.0,60.0,2.0,24.9,99.67,162.0,106.6,43.0,3.77,4.1271,95.0,3600.0,120.0,1494.0,5980.2,9720.0,6396.0,2580.0,226.20,247.6260,5700.0,4.0,49.8,199.34,324.0,213.2,86.0,7.54,8.2542,190.0,620.01,2481.783,4033.8,2654.34,1070.7,93.873,102.76479,2365.5,9934.1089,16146.54,10624.822,4285.81,375.7559,411.348057,9468.65,26244.0,17269.2,6966.0,610.74,668.5902,15390.0,11363.56,4583.8,401.882,439.94886,10127.0,1849.0,162.11,177.4653,4085.0,14.2129,15.559167,358.15,17.032954,392.0745,9025.0
440,1.0,36.0,1.0,30.0,95.00,201.0,125.2,42.0,4.79,5.1299,85.0,1296.0,36.0,1080.0,3420.0,7236.0,4507.2,1512.0,172.44,184.6764,3060.0,1.0,30.0,95.00,201.0,125.2,42.0,4.79,5.1299,85.0,900.00,2850.000,6030.0,3756.00,1260.0,143.700,153.89700,2550.0,9025.0000,19095.00,11894.000,3990.00,455.0500,487.340500,8075.00,40401.0,25165.2,8442.0,962.79,1031.1099,17085.0,15675.04,5258.4,599.708,642.26348,10642.0,1764.0,201.18,215.4558,3570.0,22.9441,24.572221,407.15,26.315874,436.0415,7225.0
441,1.0,36.0,1.0,19.6,71.00,250.0,133.2,97.0,3.00,4.5951,92.0,1296.0,36.0,705.6,2556.0,9000.0,4795.2,3492.0,108.00,165.4236,3312.0,1.0,19.6,71.00,250.0,133.2,97.0,3.00,4.5951,92.0,384.16,1391.600,4900.0,2610.72,1901.2,58.800,90.06396,1803.2,5041.0000,17750.00,9457.200,6887.00,213.0000,326.252100,6532.00,62500.0,33300.0,24250.0,750.00,1148.7750,23000.0,17742.24,12920.4,399.600,612.06732,12254.4,9409.0,291.00,445.7247,8924.0,9.0000,13.785300,276.00,21.114944,422.7492,8464.0

In [70]:
standardized_X = X1.copy()
standardized_array = scaler.transform(standardized_X)

In [71]:
standardized_array = pd.DataFrame(scaler.transform(standardized_X))
standardized_X[:] = standardized_array

In [72]:
standardized_X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65
0,0.0,0.800500,1.065488,1.297088,0.459841,-0.929746,-0.732065,-0.912316,-0.054499,0.418531,-0.370989,0.766797,1.340323,1.403562,0.823798,-0.009515,-0.081672,-0.178440,0.388878,0.833820,0.455427,1.065488,1.654667,1.095032,0.321874,0.184169,0.216988,0.546516,1.117142,0.744287,1.282848,1.087091,0.009345,-0.083393,-0.229845,0.410824,1.100308,0.612744,0.392582,-0.462571,-0.449504,-0.651972,0.095384,0.506956,0.044238,-0.903487,-0.813017,-1.112881,-0.460494,-0.536019,-0.849424,-0.736659,-1.136795,-0.460423,-0.512299,-0.735412,-0.833298,-1.043556,-0.802610,-1.038559,-0.186772,0.017080,-0.200226,0.365194,-0.040741,-0.418020
1,0.0,-0.039567,-0.938537,-1.082180,-0.553505,-0.177624,-0.402886,1.564421,-0.830301,-1.436589,-1.938479,-0.177720,-0.716088,-0.589794,-0.300687,-0.154461,-0.316895,1.061709,-0.631021,-0.562106,-0.801405,-0.938537,-1.133921,-0.957065,-0.860160,-0.855689,-0.026848,-0.963253,-1.154911,-1.269493,-1.011615,-0.966113,-0.779803,-0.805307,0.696891,-0.987162,-1.331316,-1.567858,-0.589553,-0.448867,-0.572375,1.091159,-0.866882,-1.077721,-1.362391,-0.255208,-0.388389,1.079685,-0.679633,-0.755236,-1.084359,-0.476575,0.829733,-0.697185,-0.811237,-1.022715,1.563184,0.534769,0.808197,0.283724,-0.773468,-0.988020,-1.153131,-1.351001,-1.807360,-1.734993
2,0.0,1.793307,1.065488,0.934533,-0.119214,-0.958674,-0.718897,-0.680122,-0.054499,0.060156,-0.545154,2.133417,2.104132,2.106156,1.288602,0.586307,0.453491,0.609132,0.965343,1.528326,1.136643,1.065488,1.445195,0.809522,0.303827,0.194167,0.460824,0.546516,0.971333,0.667572,0.875269,0.476056,-0.195185,-0.213008,-0.132477,0.270146,0.644681,0.277524,-0.186549,-0.751415,-0.649693,-0.671323,-0.119948,-0.078705,-0.401397,-0.926440,-0.816092,-0.975125,-0.471589,-0.682907,-0.940256,-0.726764,-0.978721,-0.454429,-0.602967,-0.779747,-0.668956,-0.717006,-0.675726,-0.883251,-0.186772,-0.079756,-0.254292,0.004070,-0.334069,-0.579359
3,0.0,-1.872441,-0.938537,-0.243771,-0.770650,0.256292,0.525397,-0.757520,0.721302,0.476983,-0.196823,-1.564402,-1.421143,-1.588914,-1.662935,-1.374548,-1.093494,-1.600507,-0.897081,-1.532185,-1.613067,-0.938537,-0.891719,-1.010598,-0.724813,-0.503237,-1.246026,-0.359345,-0.765631,-0.885916,-0.305473,-0.595515,-0.012655,0.231557,-0.888900,0.369061,0.009340,-0.293119,-0.780980,-0.296630,0.009539,-1.021961,0.203050,-0.326266,-0.618151,0.163899,0.323610,-0.486891,0.543666,0.350057,0.052752,0.399515,-0.221247,0.604256,0.592861,0.307849,-0.725123,0.262644,-0.601803,-0.818178,0.567551,0.665972,0.455319,0.425438,0.101649,-0.252930
4,0.0,0.113172,-0.938537,-0.764944,0.459841,0.082726,0.327890,0.171256,-0.054499,-0.672502,-0.980568,-0.020434,-0.657334,-0.326525,0.250519,0.092462,0.251057,0.218674,-0.010213,-0.174872,-0.326556,-0.938537,-1.042277,-0.707245,-0.778952,-0.578227,-0.758355,-0.661299,-0.999472,-1.058525,-0.757529,-0.297530,-0.443495,-0.185176,-0.305329,-0.389281,-0.837173,-0.982479,0.392582,0.294334,0.469543,0.442516,0.095384,-0.091506,-0.312977,-0.007704,0.129886,0.174338,-0.072145,-0.273649,-0.462192,0.195473,0.454200,0.022092,-0.016423,-0.175818,0.040420,0.480344,-0.097122,-0.297594,-0.186772,-0.277726,-0.389456,-0.690116,-0.951859,-0.966290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,0.0,0.876870,1.065488,0.413360,1.256040,-0.119769,-0.053957,-0.602724,-0.054499,0.655787,0.151508,0.862292,1.399077,0.934004,1.303738,0.546363,0.491803,0.129934,0.433222,1.005483,0.763942,1.065488,1.144080,1.487607,0.827171,0.699098,0.542102,0.546516,1.213673,0.974434,0.325876,0.960997,0.138074,0.122447,-0.342119,0.067922,0.577655,0.327925,1.266877,0.578682,0.492207,0.018344,0.391466,1.207670,0.867297,-0.201234,-0.172002,-0.534946,-0.149814,0.150159,-0.042178,-0.171970,-0.475661,-0.151734,0.153181,-0.015410,-0.611401,-0.608156,-0.350340,-0.517975,-0.186772,0.081189,-0.038030,0.612065,0.425020,0.088508
438,0.0,-0.115937,1.065488,-0.334410,-1.422086,1.037341,1.664355,-0.602724,0.721302,-0.380819,0.935254,-0.253955,0.635267,-0.279313,-0.711253,0.387498,0.912029,-0.475720,0.377792,-0.254755,0.221454,1.065488,0.712046,0.167127,1.549024,2.003920,0.542102,1.150423,0.791917,1.319653,-0.387184,-0.983739,0.417967,0.997377,-0.781700,0.325099,-0.433516,0.189282,-1.314961,-0.244599,0.408673,-1.184509,-0.099761,-1.133760,-0.530237,1.001454,1.455044,0.003265,0.918145,0.485275,1.265671,1.762178,0.695157,1.252354,1.145887,1.831461,-0.611401,0.534769,-0.767349,-0.190007,0.567551,0.376241,0.894601,-0.420844,0.306847,0.911615
439,0.0,0.876870,1.065488,-0.334410,0.363573,-0.785107,-0.290965,-0.525326,-0.232934,-0.985649,0.325674,0.862292,1.399077,0.473515,0.837168,0.128774,0.305419,0.196489,0.280237,0.287555,0.846764,1.065488,0.712046,1.047566,0.412105,0.519123,0.623381,0.407617,0.545835,1.051149,-0.387184,-0.058324,-0.720992,-0.402773,-0.702728,-0.348111,-0.699149,-0.102570,0.292991,-0.400575,-0.107109,-0.305350,-0.094674,-0.320407,0.388644,-0.786518,-0.549766,-0.792518,-0.508371,-0.943462,-0.455362,-0.382113,-0.580225,-0.351475,-0.587963,-0.148181,-0.552460,-0.768438,-0.934904,-0.362667,-0.336556,-0.485228,-0.131630,-0.968757,-0.392627,0.264854
440,0.0,-0.956004,-0.938537,0.821235,0.025550,0.343075,0.321306,-0.602724,0.558384,0.936163,-0.545154,-0.986618,-1.068616,-0.489324,-0.777474,-0.622887,-0.509491,-0.988197,-0.315739,-0.591863,-0.975333,-0.938537,-0.584058,-0.814311,-0.697744,-0.580727,-1.164748,-0.422756,-0.672219,-0.962631,0.752173,0.496393,0.728355,0.640112,-0.102347,0.747132,1.029236,0.206361,-0.046244,0.230741,0.251551,-0.534318,0.438907,0.470535,-0.315504,0.251681,0.238548,-0.319662,0.468188,0.621246,-0.069496,0.188836,-0.219965,0.389627,0.590984,0.001637,-0.611401,0.294754,-0.237549,-0.809502,0.395239,0.681600,0.199521,0.911809,0.110865,-0.579359
441,0.0,-0.956004,-0.938537,-1.535374,-1.711613,1.760535,0.584649,3.654168,-0.830301,-0.088752,0.064426,-0.986618,-1.068616,-1.360065,-1.322373,-0.089099,-0.385236,1.208131,-1.030111,-0.860828,-0.801405,-0.938537,-1.264840,-1.242574,-0.255609,-0.480740,1.070413,-0.963253,-0.880719,-0.828379,-1.346923,-1.700681,-0.092085,-0.444066,1.931271,-1.119048,-1.128466,-1.044098,-1.532881,-0.057247,-0.437070,1.708067,-1.189881,-1.206100,-1.095111,1.872303,1.050704,4.744641,-0.122075,1.129112,1.277054,0.462586,3.871807,-0.360024,0.415022,0.470700,4.689844,2.738980,3.989273,3.835840,-0.773468,-0.714873,-0.686816,-0.141813,-0.041353,0.001741