In [1]:
from pandas_datareader.data import DataReader
from datetime import date, datetime, timedelta
import pandas as pd

# **Exercise**
* From FRED, obtain Natural Gas prices from Jaunuary 1, 2004 to December, 2019.
* You can find the series code for this data by searching the FRED website
* Using df.mean(), compute the mean gas price over the full sample.

# **Exercise**
- Moving averages can help smooth short-term fluctuations in time-series data. 
- The df.rolling() method can compute summary statistics over trailing window. 

    
For the Natural Gas data, compute the 30-day moving average.

Next, compute the variance of the moving average.

Is this the moving average series more or less variable than raw Gas prices?

# **Exercise**
- One intriguing trading strategy compares current prices relative to their maximum over a historical window.
- Filters can help identify these opportunities.     
    - For example, we can create an indicator to identify when prices were below $20
    - ind = df['AdjClose'] < 20
    - The ind can then be applied as follows
    - filtered_close = df['AdjClose'][ind]


- Calculate on how many days:
    - Gas prices were below their trailing 30-day maximum,.

This exercise refers to NG data spanning January 1, 2004 to December 31, 2019.

In [2]:
#ng = DataReader('DHHNGSP', 'fred', start='2004-1-1', end='2019-12-31')
#ng.to_csv('data/ng.csv') 


ng = pd.read_csv('data/ng.csv', parse_dates=['DATE'], index_col='DATE')
ng.columns = ['price']
ng = ng.dropna()
ng.tail()

            price
DATE
2019-12-24   2.11
2019-12-26   2.09
2019-12-27   1.75
2019-12-30   2.06
2019-12-31   2.09

In [3]:
ng.mean()

price    4.614685
dtype: float64

In [4]:
ng_rolling = ng.rolling(window=30).mean()
ng_rolling

               price
DATE
2004-01-05       NaN
2004-01-06       NaN
2004-01-07       NaN
2004-01-08       NaN
2004-01-09       NaN
...              ...
2019-12-24  2.410000
2019-12-26  2.389000
2019-12-27  2.358667
2019-12-30  2.338000
2019-12-31  2.317667

[4030 rows x 1 columns]

In [5]:
print(ng.var())
print(ng_rolling.var())

price    5.298718
dtype: float64
price    5.088198
dtype: float64

In [6]:
rolling_high = ng['price'].rolling(window = 30).max()
ind = ng['price'] <  rolling_high
ind

DATE
2004-01-05    False
2004-01-06    False
2004-01-07    False
2004-01-08    False
2004-01-09    False
              ...
2019-12-24     True
2019-12-26     True
2019-12-27     True
2019-12-30     True
2019-12-31     True
Name: price, Length: 4030, dtype: bool

In [7]:
ng_filtered = ng['price'][ind]
ng_filtered.shape
#ng_filtered.plot()

(3572,)

In [8]:
# Alternative solution: Convert ind to a 0/1 integer, and then sum
ind.astype(int).sum()

3572